<script setup>
import {ref,computed,watch,onMounted,onUnmounted,nextTick} from 'vue';
import {PanelsTopLeft,Clapperboard,Palette,Plus,Play,Download,ChevronLeft,ChevronRight,Copy,Trash2,Check,Code2,MousePointer2,Move,RotateCcw,Upload, X, Circle, Square, Pencil, Settings2, Monitor, Save} from 'lucide-vue-next';
const themes=[{id:'mint',name:'Terminal',accent:'#a5f3cf',bg:'#101d22',panel:'#16292f',ink:'#f2f7f6'},{id:'violet',name:'Midnight',accent:'#c4b5fd',bg:'#19172c',panel:'#25233d',ink:'#f6f3ff'},{id:'amber',name:'Carbon',accent:'#f5c878',bg:'#201d18',panel:'#302b23',ink:'#fff8eb'},{id:'paper',name:'Paper',accent:'#2563eb',bg:'#f3f5f9',panel:'#e4e9f1',ink:'#142034'}];
const presets=[{id:'split',name:'Explication + code',desc:'Une idée, un exemple'},{id:'title',name:'Ouverture',desc:'Donner le ton'},{id:'code',name:'Code en grand',desc:'Lire entre les lignes'},{id:'compare',name:'Deux colonnes',desc:'Mettre en perspective'}];
function slide(title,body,code,layout='split'){return {id:crypto.randomUUID(),title,body,code,label:'SOUS LE CAPOT',layout,positions:{title:{x:112,y:215,w:680,size:76},body:{x:112,y:420,w:650,size:31},code:{x:880,y:260,w:925,size:29}}};}
const defaults=[slide('Tout commence\npar le bytecode.','Le compilateur traduit votre code Java en instructions que la JVM sait exécuter.\n\nUn même fichier .class.\nPlusieurs systèmes d’exploitation.','// HelloWorld.java\npublic class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println("Hello, Java!");\n    }\n}\n\n// Compiler, puis exécuter\n$ javac HelloWorld.java\n$ java HelloWorld'),slide('Du source\nà l’exécution.','1. Le fichier .java contient votre code.\n2. javac génère le bytecode .class.\n3. La JVM charge et exécute ce bytecode.','SOURCE .java\n      ↓ javac\nBYTECODE .class\n      ↓ JVM\nEXÉCUTION'),slide('La JVM,\nune machine à part.','Chargement des classes, vérification du bytecode, gestion de la mémoire : la JVM fait bien plus qu’exécuter des instructions.','ClassLoader\n    ↓\nBytecode verifier\n    ↓\nInterpreter + JIT compiler\n    ↓\nNative machine code'),slide('À retenir.','Java est compilé en bytecode.\nLa JVM exécute ce bytecode.\nLe JIT peut compiler les portions fréquemment exécutées en code natif.','javac ≠ JVM\nbytecode ≠ code machine\n\nComprendre avant d’automatiser.','title')];
let initial;try{initial=JSON.parse(localStorage.getItem('frame-project')||'null');}catch{}
const slides=ref(initial?.slides?.length?initial.slides:defaults),project=ref(initial?.project||'Java, sous le capot'),themeId=ref(initial?.themeId||'mint'),index=ref(0),view=ref('slides'),tab=ref('content'),selected=ref('title'),presenting=ref(false),canvas=ref(null),toast=ref(''),saved=ref(true),zoom=ref(100),recording=ref(false),elapsed=ref(0),laser=ref('#ff756d'),laserSize=ref(12),tool=ref('laser'),banner=ref(initial?.banner||{title:'Le bytecode, expliqué.',subtitle:'JAVA · SOUS LE CAPOT',type:'lower',name:'Killian'});
const lastExport=ref(null),videoPreview=ref(false),videoMeta=ref(''),finalizing=ref(false);
const current=computed(()=>slides.value[index.value]),theme=computed(()=>themes.find(t=>t.id===themeId.value)||themes[0]),position=computed(()=>current.value.positions[selected.value]);
let toastTimer,saveTimer,recorder,chunks=[],stream,animation,timer,started=0,drag=null,pointer=null,strokes=[],activeStroke=null;
function notify(message){toast.value=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value='',3200);}
watch([slides,project,themeId,banner],()=>{saved.value=false;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('frame-project',JSON.stringify({slides:slides.value,project:project.value,themeId:themeId.value,banner:banner.value}));saved.value=true;}catch{notify('Sauvegarde locale impossible. Exportez votre projet.');}},450);draw();},{deep:true});
watch([index,view,selected,presenting,zoom],async()=>{pointer=null;strokes=[];await nextTick();draw();});
function add(){slides.value.push(slide('Une nouvelle idée.','Ajoutez votre explication ici.','// Votre exemple Java'));index.value=slides.value.length-1;tab.value='content';}
function duplicate(){let s=JSON.parse(JSON.stringify(current.value));s.id=crypto.randomUUID();slides.value.splice(index.value+1,0,s);index.value++;notify('Diapo dupliquée');}
function remove(){if(slides.value.length===1)return;slides.value.splice(index.value,1);index.value=Math.min(index.value,slides.value.length-1);}
function applyPreset(id){current.value.layout=id;const p=current.value.positions;p.title={x:112,y:id==='title'?300:215,w:id==='title'?1650:680,size:id==='title'?100:76};p.body={x:112,y:id==='title'?580:420,w:id==='title'?1600:650,size:31};p.code={x:id==='code'?112:880,y:id==='code'?365:260,w:id==='code'?1690:925,size:29};notify('Composition appliquée');}
function download(blob,name){if(lastExport.value)URL.revokeObjectURL(lastExport.value.url);const url=URL.createObjectURL(blob);lastExport.value={url,name,size:Math.max(1,Math.round(blob.size/1024)),video:blob.type.startsWith('video/')};const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();if(lastExport.value.video){videoMeta.value='';videoPreview.value=true;}}
function exportProject(){download(new Blob([JSON.stringify({version:1,project:project.value,slides:slides.value,themeId:themeId.value,banner:banner.value},null,2)],{type:'application/json'}),'frame-projet.json');notify('Projet exporté');}
async function importProject(event){try{const data=JSON.parse(await event.target.files[0].text());if(!Array.isArray(data.slides)||!data.slides.length||data.slides.length>100||!data.slides.every(s=>typeof s.title==='string'&&typeof s.body==='string'&&typeof s.code==='string'&&typeof s.label==='string'&&presets.some(p=>p.id===s.layout)&&['title','body','code'].every(k=>s.positions?.[k]&&['x','y','w','size'].every(n=>Number.isFinite(s.positions[k][n])))))throw Error();slides.value=data.slides;project.value=String(data.project||'Projet importé');themeId.value=themes.some(t=>t.id===data.themeId)?data.themeId:'mint';if(data.banner&&typeof data.banner.title==='string'&&typeof data.banner.subtitle==='string'&&['lower','chapter','tip'].includes(data.banner.type))banner.value=data.banner;index.value=0;notify('Projet importé');}catch{notify('Ce fichier n’est pas un projet Frame valide.');}event.target.value='';}
function round(ctx,x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function text(ctx,value,x,y,maxWidth,size,color,weight=400,font='Arial'){ctx.fillStyle=color;ctx.font=`${weight} ${size}px ${font}`;ctx.textBaseline='top';let row=0;String(value).split('\n').forEach(line=>{let words=line.split(' '),out='';for(const word of words){let test=out?out+' '+word:word;if(ctx.measureText(test).width>maxWidth&&out){ctx.fillText(out,x,y+row*size*1.35);row++;out=word;}else out=test;}ctx.fillText(out,x,y+row*size*1.35);row++;});return row*size*1.35;}
function render(ctx,s,n,{overlay=false,transparent=false}={}){const t=theme.value;ctx.clearRect(0,0,1920,1080);if(!transparent&&!overlay){ctx.fillStyle=t.bg;ctx.fillRect(0,0,1920,1080);ctx.fillStyle=t.accent+'09';for(let x=0;x<1920;x+=40)for(let y=0;y<1080;y+=40)ctx.fillRect(x,y,1.5,1.5);}
if(overlay){const b=banner.value;if(b.type==='lower'){round(ctx,110,800,Math.min(1650,Math.max(900,ctx.measureText(b.title).width+300)),190,16,t.bg);round(ctx,110,800,9,190,4,t.accent);text(ctx,b.subtitle,155,835,1600,25,t.accent,700);text(ctx,b.title,155,883,1600,48,t.ink,700);}else if(b.type==='chapter'){round(ctx,200,385,1520,300,20,t.bg);text(ctx,b.subtitle,265,435,1370,27,t.accent,700);text(ctx,b.title,265,495,1370,64,t.ink,700);}else{round(ctx,1080,80,730,240,16,t.bg);text(ctx,'À RETENIR',1120,112,640,24,t.accent,700);text(ctx,b.title,1120,163,640,42,t.ink,700);}return;}
text(ctx,'JAVA / SOUS LE CAPOT',112,75,900,22,t.accent,700);text(ctx,String(n+1).padStart(2,'0')+' / '+String(slides.value.length).padStart(2,'0'),1660,75,200,22,t.ink,400,'monospace');
const p=s.positions;round(ctx,112,155,Math.max(180,s.label.length*13+38),39,6,t.accent+'18');text(ctx,s.label,130,164,1000,19,t.accent,700);
if(s.layout!=='code')text(ctx,s.title,p.title.x,p.title.y,p.title.w,p.title.size,t.ink,700);else text(ctx,s.title,p.title.x,p.title.y,1690,66,t.ink,700);
if(s.layout!=='code')text(ctx,s.body,p.body.x,p.body.y,p.body.w,p.body.size,t.ink+'b8');
if(s.layout!=='title'){round(ctx,p.code.x,p.code.y,p.code.w,Math.max(420,s.code.split('\n').length*p.code.size*1.6+125),18,t.panel);text(ctx,s.layout==='compare'?'EN PRATIQUE':'HelloWorld.java',p.code.x+32,p.code.y+25,p.code.w-64,21,t.ink+'80',400,'monospace');ctx.strokeStyle=t.ink+'15';ctx.beginPath();ctx.moveTo(p.code.x+24,p.code.y+75);ctx.lineTo(p.code.x+p.code.w-24,p.code.y+75);ctx.stroke();s.code.split('\n').forEach((line,i)=>{text(ctx,String(i+1).padStart(2,' '),p.code.x+28,p.code.y+108+i*p.code.size*1.6,50,p.code.size*.75,t.ink+'35',400,'monospace');text(ctx,line,p.code.x+82,p.code.y+103+i*p.code.size*1.6,p.code.w-110,p.code.size,line.trim().startsWith('//')?t.ink+'65':/public|class|static|void/.test(line)?t.accent:t.ink,400,'monospace');});}
ctx.strokeStyle=t.ink+'18';ctx.beginPath();ctx.moveTo(112,972);ctx.lineTo(1808,972);ctx.stroke();text(ctx,project.value,112,1005,1500,20,t.ink+'60');text(ctx,'FRAME',1710,1005,120,20,t.accent,700);
}
function draw(){if(!canvas.value||!current.value)return;const ctx=canvas.value.getContext('2d');render(ctx,current.value,index.value,{overlay:view.value==='banners'});if(presenting.value){ctx.lineCap='round';ctx.lineJoin='round';for(const stroke of strokes){ctx.strokeStyle=stroke.color;ctx.lineWidth=stroke.size;ctx.beginPath();stroke.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();}if(pointer&&tool.value==='laser'){ctx.fillStyle=laser.value;ctx.shadowColor=laser.value;ctx.shadowBlur=22;ctx.beginPath();ctx.arc(pointer.x,pointer.y,laserSize.value,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}}else if(view.value==='slides'){const p=position.value;ctx.strokeStyle=theme.value.accent+'80';ctx.lineWidth=2;ctx.setLineDash([8,8]);ctx.strokeRect(p.x-12,p.y-12,p.w+24,selected.value==='title'?p.size*1.35*current.value.title.split('\n').length+24:selected.value==='body'?p.size*1.35*current.value.body.split('\n').length+55:Math.max(420,current.value.code.split('\n').length*p.size*1.6+125)+24);ctx.setLineDash([]);}}
function thumbnail(s,n){const c=document.createElement('canvas');c.width=1920;c.height=1080;render(c.getContext('2d'),s,n);return c.toDataURL('image/jpeg',.35);}
function coords(e){const r=canvas.value.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*1920,y:(e.clientY-r.top)/r.height*1080};}
function down(e){if(view.value==='banners'&&!presenting.value)return;canvas.value.setPointerCapture(e.pointerId);const p=coords(e);if(presenting.value){pointer=p;if(tool.value==='pen'){activeStroke={color:laser.value,size:laserSize.value/2,points:[p]};strokes.push(activeStroke);}draw();}else{const blocks=['code','body','title'];const hit=blocks.find(k=>{const b=current.value.positions[k];return p.x>=b.x-20&&p.x<=b.x+b.w+20&&p.y>=b.y-20&&p.y<=b.y+(k==='code'?600:k==='title'?220:350);});if(hit)selected.value=hit;drag={p,origin:{...position.value}};}}
function move(e){const p=coords(e);if(presenting.value){pointer=p;if(activeStroke)activeStroke.points.push(p);draw();}else if(drag){position.value.x=Math.round(Math.max(0,Math.min(1850,drag.origin.x+p.x-drag.p.x)));position.value.y=Math.round(Math.max(0,Math.min(1000,drag.origin.y+p.y-drag.p.y)));draw();}}
function up(){drag=null;activeStroke=null;}
function leave(){if(!recording.value){pointer=null;draw();}}
async function png(){const c=document.createElement('canvas');c.width=1920;c.height=1080;render(c.getContext('2d'),current.value,index.value,{overlay:view.value==='banners',transparent:view.value==='banners'});c.toBlob(b=>{if(b)download(b,view.value==='banners'?'frame-bandeau.png':`frame-diapo-${index.value+1}.png`);},'image/png');notify(view.value==='banners'?'Bandeau PNG transparent exporté':'Diapo PNG exportée');}
async function startPresentation(){view.value='slides';presenting.value=true;await nextTick();draw();}
function exit(){if(recording.value)stopRecord();presenting.value=false;strokes=[];}
async function startRecord(){if(finalizing.value)return;if(!canvas.value?.captureStream||!window.MediaRecorder){notify('L’enregistrement nécessite un navigateur récent (Chrome ou Firefox).');return;}try{chunks=[];stream=canvas.value.captureStream(30);const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw Error();recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:10000000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{download(new Blob(chunks,{type:mime}),'frame-presentation.webm');stream.getTracks().forEach(t=>t.stop());notify('Vidéo WebM exportée');};recorder.start(1000);recording.value=true;started=Date.now();elapsed.value=0;timer=setInterval(()=>elapsed.value=Math.floor((Date.now()-started)/1000),1000);const frame=()=>{draw();animation=requestAnimationFrame(frame);};frame();}catch{notify('Impossible de lancer l’enregistrement dans ce navigateur.');}}
function stopRecord(){if(!recording.value)return;recording.value=false;finalizing.value=true;clearInterval(timer);cancelAnimationFrame(animation);const finish=recorder.onstop;recorder.onstop=()=>{finish();finalizing.value=false;};recorder.stop();}
function navigate(delta){index.value=Math.max(0,Math.min(slides.value.length-1,index.value+delta));}
function keys(e){if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(presenting.value){if(e.key==='ArrowRight'||e.key===' ') {e.preventDefault();navigate(1);}if(e.key==='ArrowLeft')navigate(-1);if(e.key==='Escape'){if(videoPreview.value)videoPreview.value=false;else exit();}}}
onMounted(()=>{draw();window.addEventListener('keydown',keys);if(document.modelContext?.registerTool)try{document.modelContext.registerTool({name:'read_frame_project',description:'Read the current slide project',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return {project:project.value,theme:themeId.value,slides:slides.value.map(({title,body,code,layout})=>({title,body,code,layout}))};}});}catch{}});
onUnmounted(()=>{window.removeEventListener('keydown',keys);clearInterval(timer);cancelAnimationFrame(animation);stream?.getTracks().forEach(t=>t.stop());});
</script>

<template>
<div class="studio" :class="{presenting}">
 <aside class="rail" v-if="!presenting">
  <a class="brand" href="#" @click.prevent="view='slides'" aria-label="Frame accueil"><span class="brand-icon">f</span><span>frame<span class="brand-dot">.</span></span></a>
  <div class="workspace-label">TON ATELIER</div>
  <button :class="{active:view==='slides'}" @click="view='slides'"><PanelsTopLeft :size="19"/>Diaporamas</button>
  <button :class="{active:view==='banners'}" @click="view='banners'"><Clapperboard :size="19"/>Incrustations</button>
  <button :class="{active:view==='themes'}" @click="view='themes'"><Palette :size="19"/>Thèmes</button>
  <div class="rail-bottom"><div class="personal-avatar">K</div><div>Mon espace<span>Studio personnel</span></div><span class="version">v1</span></div>
 </aside>
 <div class="main-shell">
  <header v-if="!presenting"><div class="breadcrumb">Mon studio <span>/</span> {{view==='slides'?'Diaporamas':view==='banners'?'Incrustations':'Thèmes'}}</div><div class="header-right"><span class="save-state"><Check :size="14" v-if="saved"/>{{saved?'Sauvegardé sur cet appareil':'Sauvegarde…'}}</span><label class="icon-btn" title="Importer un projet"><Upload :size="17"/><input type="file" accept="application/json" hidden @change="importProject"></label><button class="icon-btn" title="Exporter le projet JSON" @click="exportProject"><Save :size="17"/></button><span class="avatar">K</span></div></header>
  <div class="project-bar" v-if="!presenting"><div><div class="eyebrow">{{view==='banners'?'HABILLAGE VIDÉO':view==='themes'?'IDENTITÉ VISUELLE':'DIAPORAMA'}}</div><input v-model="project" class="project-name" aria-label="Nom du projet"><span class="project-meta" v-if="view==='slides'">{{slides.length}} diapos <span>·</span> 16:9 <span>·</span> 1920 × 1080</span></div><div class="project-actions"><button class="btn" @click="png" v-if="view!=='themes'"><Download :size="16"/>{{view==='banners'?'Exporter le PNG':'Exporter la diapo'}}</button><button class="btn primary" @click="startPresentation"><Play :size="16"/>Présenter</button></div></div>
  <template v-if="view==='themes'">
   <section class="theme-page"><h2>Une identité. Toutes tes créations.</h2><p>Le thème s’applique à toutes les diapos et à tes incrustations.</p><div class="theme-grid"><button v-for="t in themes" :key="t.id" :class="['theme-card',{chosen:themeId===t.id}]" @click="themeId=t.id"><div class="theme-example" :style="{background:t.bg,color:t.ink}"><span :style="{color:t.accent}">JAVA / SOUS LE CAPOT</span><strong>Comprendre.<br>Construire.</strong><div :style="{background:t.panel,color:t.accent}">public class HelloWorld { }</div></div><div class="theme-caption">{{t.name}}<Check v-if="themeId===t.id" :size="18"/></div></button></div></section>
  </template>
  <div class="editor" v-else>
   <aside class="slides-panel" v-if="view==='slides'&&!presenting"><div class="panel-heading">Diapos <span>{{slides.length}}</span><button class="icon-btn" @click="add" title="Ajouter une diapo"><Plus :size="17"/></button></div><div class="slide-list"><button v-for="(s,n) in slides" :key="s.id" :class="['slide-item',{chosen:index===n}]" @click="index=n"><div class="slide-thumb"><img :src="thumbnail(s,n)" alt=""><span class="slide-number">{{String(n+1).padStart(2,'0')}}</span></div><span class="slide-title">{{s.title.replaceAll('\n',' ')}}</span></button></div><button class="add-slide" @click="add"><Plus :size="16"/>Ajouter une diapo</button><div class="slide-actions"><button class="icon-btn" @click="duplicate" title="Dupliquer"><Copy :size="16"/></button><button class="icon-btn" @click="remove" :disabled="slides.length===1" title="Supprimer la diapo"><Trash2 :size="16"/></button></div></aside>
   <aside class="slides-panel banner-presets" v-if="view==='banners'"><div class="panel-heading">Formats</div><button v-for="b in [{id:'lower',name:'Bandeau de titre',sub:'En bas de la vidéo'},{id:'chapter',name:'Titre de chapitre',sub:'Au centre de la vidéo'},{id:'tip',name:'À retenir',sub:'Dans le coin supérieur'}]" :key="b.id" :class="['format-card',{chosen:banner.type===b.id}]" @click="banner.type=b.id"><Clapperboard :size="26"/><strong>{{b.name}}</strong><span>{{b.sub}}</span></button><div class="format-note">PNG transparent<br>1920 × 1080</div></aside>
   <section class="work-area">
    <div class="canvas-toolbar" v-if="!presenting"><span><Monitor :size="15"/>{{view==='banners'?'Aperçu de l’incrustation':presets.find(p=>p.id===current.layout)?.name}}</span><div><span class="resolution">FULL HD</span><span class="divider"></span><button class="icon-btn" @click="zoom=Math.max(60,zoom-10)" title="Dézoomer">−</button><span>{{zoom}} %</span><button class="icon-btn" @click="zoom=Math.min(100,zoom+10)" title="Zoomer">+</button></div></div>
    <div class="canvas-space" :class="{'checker':view==='banners'}"><canvas ref="canvas" width="1920" height="1080" :style="{width:presenting?'100%':zoom+'%'}" @pointerdown="down" @pointermove="move" @pointerup="up" @pointercancel="up" @pointerleave="leave" aria-label="Diapo modifiable : sélectionner un bloc et le déplacer"/></div>
    <div class="canvas-bottom" v-if="!presenting"><span><MousePointer2 :size="14"/>{{view==='banners'?'Le fond sera transparent à l’export.':'Clique sur un bloc pour le déplacer.'}}</span><div v-if="view==='slides'"><button class="icon-btn" @click="navigate(-1)" :disabled="index===0" title="Diapo précédente"><ChevronLeft :size="16"/></button><span>{{index+1}} <span class="muted">/ {{slides.length}}</span></span><button class="icon-btn" @click="navigate(1)" :disabled="index===slides.length-1" title="Diapo suivante"><ChevronRight :size="16"/></button></div></div>
    <div class="speaker-note" v-if="!presenting&&view==='slides'"><div class="note-icon"><Code2 :size="20"/></div><div><strong>Le contenu d’abord. Le design suit.</strong><p>Un thème commun, des compositions prêtes à l’emploi. Garde ton énergie pour Java.</p></div><span>⌘ studio</span></div>
    <div class="present-controls" v-if="presenting"><button class="icon-btn" @click="exit" title="Quitter (Échap)"><X :size="19"/></button><span class="divider"></span><button class="icon-btn" @click="navigate(-1)" :disabled="index===0" title="Diapo précédente"><ChevronLeft :size="20"/></button><span>{{index+1}} / {{slides.length}}</span><button class="icon-btn" @click="navigate(1)" :disabled="index===slides.length-1" title="Diapo suivante"><ChevronRight :size="20"/></button><span class="divider"></span><button :class="['icon-btn',{active:tool==='laser'}]" @click="tool='laser'" title="Laser"><MousePointer2 :size="19"/></button><button :class="['icon-btn',{active:tool==='pen'}]" @click="tool='pen'" title="Dessiner en maintenant la souris"><Pencil :size="19"/></button><input type="color" v-model="laser" aria-label="Couleur du pointeur"><input class="laser-range" type="range" min="4" max="30" v-model.number="laserSize" aria-label="Taille du pointeur"><button class="icon-btn" @click="strokes=[];draw()" title="Effacer les annotations"><RotateCcw :size="18"/></button><button :disabled="finalizing" :class="['btn',recording?'danger':'primary']" @click="recording?stopRecord():startRecord()"><Square v-if="recording" :size="14"/><Circle v-else :size="14"/>{{recording?'Stop · '+Math.floor(elapsed/60)+':'+String(elapsed%60).padStart(2,'0'):'Enregistrer'}}</button></div>
   </section>
   <aside class="inspector" v-if="!presenting">
    <div class="inspector-tabs" v-if="view==='slides'"><button :class="{active:tab==='content'}" @click="tab='content'">Contenu</button><button :class="{active:tab==='layout'}" @click="tab='layout'">Composition</button></div><div class="panel-heading" v-else>Personnaliser</div>
    <div class="inspector-body" v-if="view==='banners'"><label>Surtitre<input v-model="banner.subtitle"></label><label>Texte du bandeau<textarea v-model="banner.title" rows="4"></textarea></label><div class="section-label">THÈME</div><div class="swatches"><button v-for="t in themes" :key="t.id" :style="{background:t.accent}" :class="{chosen:themeId===t.id}" @click="themeId=t.id" :title="t.name" :aria-label="t.name"><Check v-if="themeId===t.id" :size="15"/></button></div><p class="field-help">Le thème est partagé avec ton diaporama.</p><button class="btn primary full" @click="png"><Download :size="16"/>Télécharger le bandeau</button></div>
    <div class="inspector-body" v-else-if="tab==='content'"><div class="section-label">TEXTE DE LA DIAPO</div><label>Surtitre<input v-model="current.label"></label><label>Titre<textarea v-model="current.title" rows="3" @focus="selected='title'"></textarea></label><label>Explication<textarea v-model="current.body" rows="6" @focus="selected='body'"></textarea></label><label><span class="label-row">Exemple de code <span>JAVA</span></span><textarea class="code-input" v-model="current.code" rows="9" spellcheck="false" @focus="selected='code'"></textarea></label><p class="field-help">Les retours à la ligne sont conservés.</p></div>
    <div class="inspector-body" v-else><div class="section-label">COMPOSITIONS</div><button v-for="p in presets" :key="p.id" :class="['preset',{chosen:current.layout===p.id}]" @click="applyPreset(p.id)"><span class="layout-icon" :class="p.id"><i></i><i></i></span><span><strong>{{p.name}}</strong><small>{{p.desc}}</small></span><Check v-if="current.layout===p.id" :size="15"/></button><div class="section-label spaced">AJUSTEMENTS PRÉCIS</div><label>Bloc<select v-model="selected"><option value="title">Titre</option><option value="body">Explication</option><option value="code">Code</option></select></label><div class="position-grid"><label>X<input type="number" min="0" max="1920" v-model.number="position.x"></label><label>Y<input type="number" min="0" max="1080" v-model.number="position.y"></label><label>Largeur<input type="number" min="50" max="1920" v-model.number="position.w"></label><label>Taille du texte<input type="number" min="10" max="150" v-model.number="position.size"></label></div><div class="section-label spaced">THÈME GLOBAL</div><div class="swatches"><button v-for="t in themes" :key="t.id" :style="{background:t.accent}" :class="{chosen:themeId===t.id}" @click="themeId=t.id" :title="t.name" :aria-label="t.name"><Check v-if="themeId===t.id" :size="15"/></button></div><p class="field-help">Appliqué à toutes les diapos et incrustations.</p></div>
   </aside>
  </div>
 </div><div class="toast" role="status" v-if="toast"><Check :size="17"/>{{toast}}</div>
</div>
<div v-if="videoPreview&&lastExport?.video" class="export-backdrop" @click.self="videoPreview=false"><section class="export-dialog" role="dialog" aria-modal="true" aria-label="Votre enregistrement"><div class="export-heading"><div><strong>Ton enregistrement est prêt.</strong><p>{{lastExport.size}} Ko · WebM <span v-if="videoMeta">· {{videoMeta}}</span></p></div><button class="icon-btn" @click="videoPreview=false" title="Fermer l’aperçu"><X :size="20"/></button></div><video :src="lastExport.url" controls @loadedmetadata="videoMeta=$event.target.videoWidth+' × '+$event.target.videoHeight"/><a class="btn primary" :href="lastExport.url" :download="lastExport.name"><Download :size="16"/>Télécharger la vidéo</a></section></div>
<a v-if="lastExport&&!videoPreview&&!presenting" class="last-export" :href="lastExport.url" :download="lastExport.name"><Download :size="15"/>{{lastExport.name}} · {{lastExport.size}} Ko</a>
</template>
