<script setup>
import { Menu, PanelsTopLeft, Clapperboard, Palette, Plus, Play, Download, ChevronLeft, ChevronRight, ChevronDown, ChevronUp, Copy, Trash2, Check, Code2, MousePointer2, RotateCcw, Upload, X, Circle, Square, Pencil, Monitor, Save, GripVertical, ImagePlus, Type, LayoutGrid } from 'lucide-vue-next';
import { useStudio } from './useStudio.js';
import { colorFields } from './themes.js';
import { presets, visibleBlocks, blockLabel } from './model.js';
import PropertiesPanel from './components/PropertiesPanel.vue';
import ThemePreview from './components/ThemePreview.vue';
import InlineEditor from './components/InlineEditor.vue';
import ShapeGallery from './components/ShapeGallery.vue';
import DeckCanvas from './components/DeckCanvas.vue';
import LayoutGallery from './components/LayoutGallery.vue';
const studio=useStudio();
function themeHex(event,key,commit=true){const value=event.target.value;if(/^#[\da-f]{6}$/i.test(value))studio.themeEditor.value[key]=value;else if(commit){event.target.value=studio.themeEditor.value[key];studio.notify('Couleur au format #RRGGBB.');}}
const { fileName,fileDirty,fileBusy,fileSupported,openSupported,openProject,saveProject, selectedTextStyle, rotationHandle,rotateDown, shapeGallery,openShapes,addShape, routeMode,routeStart,routeBackup,setRouteMode,setRouteStart,traceRoute,connectSlides,undoRoute, palette:themes,themeEditor,themeUndo,openTheme,saveTheme,deleteTheme,undoTheme,panels,displayMenu,resizePanel,selectedKeys,selectedSlides,selectSlide,deselect,countdown,previewVisible, altHeld, contextMenu, codeCaption, handles, resizeDown, duplicateSelected, openContext, dismissContext, resolution, formatOpen, formatWidth, applyFormat, editSize, undoLayout, canUndoLayout, workspace, listDrag, listTarget, selectedType, editedText, exitLabel, changeText, addBlock, removeBlock, uploadImage, reorder, listDown, moveGrid, slides, project, themeId, frame, banner, index, view, tab, selected, presenting, canvas, stage, stageWidth, toast, saved, zoom, recording, elapsed, laser, laserSize, tool, lastExport, videoPreview, videoMeta, finalizing, gallery, editing, formatting, thumbs, step, transitionMs, moving, gridDraft, current, theme, position, orders, editStyle, add, chooseLayout, addMemory, applyPreset, duplicate, remove, applyGrid, setPosition, updateFragment, formatCode, exportProject, importProject, png, startPresentation, exit, startRecord, stopRecord, navigate, advance, retreat, goDirection, canGo, chooseSlide, down, move, up, leave, doubleClick, closeEdit, editSelected, clearAnnotations } = studio;
</script>

<template>
<div class="studio" :class="{presenting,'rail-collapsed':panels.collapsed,'rail-hidden':!panels.rail}" :style="{'--inspector-width':panels.inspectorWidth+'px','--slides-width':panels.slidesWidth+'px'}">
 <aside class="rail" v-if="!presenting&&panels.rail">
  <button class="rail-toggle" @click="panels.collapsed=!panels.collapsed" aria-label="Réduire ou développer la navigation"><Menu :size="20"/></button>
  <a class="brand" href="#" @click.prevent="view='slides'" aria-label="Frame accueil"><span class="brand-icon">f</span><span>frame<span class="brand-dot">.</span></span></a>
  <div class="workspace-label">TON ATELIER</div>
  <button :class="{active:view==='slides'}" @click="view='slides'"><PanelsTopLeft :size="19"/>Diaporamas</button>
  <button :class="{active:view==='banners'}" @click="view='banners'"><Clapperboard :size="19"/>Incrustations</button>
  <button :class="{active:view==='themes'}" @click="view='themes'"><Palette :size="19"/>Thèmes</button>
  <div class="rail-bottom"><div class="personal-avatar">K</div><div>Mon espace<span>Studio personnel</span></div><span class="version">v1</span></div>
 </aside>
 <div class="main-shell">
  <header v-if="!presenting"><div class="breadcrumb"><button class="icon-btn" @click="panels.rail=!panels.rail" title="Afficher ou masquer la navigation"><Menu :size="18"/></button> Mon studio <span>/</span> {{view==='slides'?'Diaporamas':view==='banners'?'Incrustations':'Thèmes'}}</div><div class="header-right"><div class="display-settings"><button class="btn" @click="displayMenu=!displayMenu" :aria-expanded="displayMenu">Affichage</button><div v-if="displayMenu" class="display-menu"><label v-for="[key,name] in [['rail','Navigation'],['properties','Propriétés'],['slides','Liste / formats'],['toolbar','Barre d’outils']]" :key="key"><input type="checkbox" v-model="panels[key]">{{name}}</label></div></div><span class="save-state"><Check :size="14" v-if="saved"/>{{saved?'Sauvegardé sur cet appareil':'Sauvegarde…'}}</span><button v-if="openSupported" class="icon-btn" title="Ouvrir un fichier lié" aria-label="Ouvrir un fichier lié" @click="openProject" :disabled="fileBusy"><Upload :size="17"/></button><label v-else class="icon-btn" title="Importer un projet"><Upload :size="17"/><input type="file" accept="application/json" hidden @change="importProject"></label><div class="file-actions"><span v-if="fileName" class="linked-file" :title="fileName">{{fileName}}{{fileDirty?' •':' ✓'}}</span><button class="icon-btn" title="Enregistrer · Ctrl S" aria-label="Enregistrer le projet" @click="saveProject(false)" :disabled="fileBusy"><Save :size="17"/></button><details class="file-menu"><summary aria-label="Options du fichier">⌄</summary><div><strong>{{fileName||'Projet sans fichier lié'}}{{fileName&&fileDirty?' · modifié':''}}</strong><button @click="saveProject(true)" :disabled="fileBusy">Enregistrer sous… · Ctrl Maj S</button><button @click="exportProject">Télécharger une copie JSON</button><label>Importer une copie JSON<input type="file" accept="application/json" @change="importProject"></label><p>{{fileSupported?'Ctrl S met à jour le fichier lié. La session est aussi sauvegardée sur cet appareil.':'Ce navigateur conserve la session locale et télécharge un JSON. Pour écrire dans un fichier lié, utilise Chrome ou Edge.'}}</p></div></details></div><span class="avatar">K</span></div></header>
  <div class="project-bar" v-if="!presenting"><div><div class="eyebrow">{{view==='banners'?'HABILLAGE VIDÉO':view==='themes'?'IDENTITÉ VISUELLE':'DIAPORAMA'}}</div><input v-model="project" class="project-name" aria-label="Nom du projet"><span class="project-meta" v-if="view==='slides'">{{slides.length}} diapos <span>·</span> 16:9 <span>·</span> <button class="format-trigger" @click="formatWidth=resolution.width;formatOpen=true">{{resolution.width}} × {{resolution.height}} ↗</button></span></div><div class="project-actions"><div class="workspace-switch" v-if="view==='slides'"><button :class="{active:workspace==='canvas'}" @click="workspace='canvas';closeEdit()"><LayoutGrid :size="15"/>Canvas</button><button :class="{active:workspace==='editor'}" @click="workspace='editor'"><Monitor :size="15"/>Éditer</button></div><button class="btn" @click="png" v-if="view!=='themes'"><Download :size="16"/>{{view==='banners'?'Exporter le PNG':'Exporter la diapo'}}</button><button class="btn primary" @click="startPresentation()"><Play :size="16"/>Présenter</button></div></div>
  <template v-if="view==='themes'">
   <section class="theme-page"><h2>Une identité. Toutes tes créations.</h2><p>Le thème s’applique à toutes les diapos et à tes incrustations.</p><div class="theme-page-actions"><button class="btn primary" @click="openTheme()"><Plus :size="16"/>Créer un thème</button><button v-if="themeUndo" class="btn" @click="undoTheme">Annuler la suppression</button></div><div class="theme-grid"><article v-for="t in themes" :key="t.id" :class="['theme-card',{chosen:themeId===t.id}]"><button class="theme-select" @click="themeId=t.id" :aria-label="'Appliquer '+t.name"><ThemePreview :theme="t"/><div class="theme-caption"><div>{{t.name}}<small class="theme-description">{{t.desc}}</small></div><Check v-if="themeId===t.id" :size="18"/></div></button><div class="theme-card-actions"><button class="btn" @click="openTheme(t)">Éditer</button><button class="icon-btn" @click="openTheme(t,true)" :aria-label="'Dupliquer '+t.name" title="Créer à partir de ce thème"><Copy :size="16"/></button><button class="icon-btn" @click="deleteTheme(t.id)" :aria-label="'Supprimer '+t.name" :disabled="themes.length===1"><Trash2 :size="16"/></button></div></article></div></section>
</template>
  <div class="editor" v-else>
   <aside class="slides-panel" v-if="view==='slides'&&!presenting&&workspace==='editor'&&panels.slides"><button class="panel-resizer right" @pointerdown="resizePanel($event,'slidesWidth')" aria-label="Redimensionner la liste"></button><div class="panel-heading">Diapos <span>{{slides.length}}</span><button class="icon-btn" @click="add" title="Ajouter une diapo"><Plus :size="17"/></button></div><div class="slide-list"><div v-for="(s,n) in slides" :key="s.id" :data-slide-index="n" :class="['slide-row',{'drop-target':listDrag!==null&&listTarget===n,sorting:listDrag===n}]"><button class="slide-grip" @pointerdown="listDown($event,n)" @keydown.up.prevent="reorder(n,Math.max(0,n-1))" @keydown.down.prevent="reorder(n,Math.min(slides.length-1,n+1))" :aria-label="'Déplacer la diapo '+(n+1)" title="Glisser pour réordonner · flèches ↑ ↓ au clavier"><GripVertical :size="15"/></button><button :class="['slide-item',{chosen:selectedSlides.includes(s.id)}]" @pointerdown="listDown($event,n)" @click="selectSlide(n,$event)"><div class="slide-thumb"><img :src="thumbs[s.id]" alt="" draggable="false"><span class="slide-number">{{String(n+1).padStart(2,'0')}}</span></div><span class="slide-title">{{s.title.replaceAll('\n',' ')}}</span></button></div></div><button class="add-slide" @click="add"><Plus :size="16"/>Ajouter une diapo</button><div class="slide-actions"><button class="icon-btn" @click="duplicate" title="Dupliquer"><Copy :size="16"/></button><button class="icon-btn" @click="remove" :disabled="slides.length===1" title="Supprimer la diapo"><Trash2 :size="16"/></button></div></aside>
   <aside class="slides-panel banner-presets" v-if="view==='banners'&&panels.slides"><div class="panel-heading">Formats</div><button v-for="b in [{id:'lower',name:'Bandeau de titre',sub:'En bas de la vidéo'},{id:'chapter',name:'Titre de chapitre',sub:'Au centre de la vidéo'},{id:'tip',name:'À retenir',sub:'Dans le coin supérieur'},{id:'video',name:'Voir une autre vidéo',sub:'Pour approfondir le sujet'}]" :key="b.id" :class="['format-card',{chosen:banner.type===b.id}]" @click="banner.type=b.id"><Clapperboard :size="26"/><strong>{{b.name}}</strong><span>{{b.sub}}</span></button><div class="format-note">PNG transparent<br>{{resolution.width}} × {{resolution.height}}</div></aside>
   <DeckCanvas v-if="view==='slides'&&!presenting&&workspace==='canvas'" :slides="slides" :thumbs="thumbs" :index="index" :selection="selectedSlides" :route-mode="routeMode" :route-start="routeStart" :can-undo="!!routeBackup" @mode="setRouteMode" @start="setRouteStart" @trace="traceRoute" @connect="connectSlides" @undo="undoRoute" @deselect="deselect" @select="selectSlide" @edit="chooseSlide($event);workspace='editor'" @move="moveGrid" @add="add"/>
   <section class="work-area" v-else>
    <div class="canvas-toolbar" v-if="!presenting&&panels.toolbar"><span><Monitor :size="15"/>{{view==='banners'?'Aperçu de l’incrustation':presets.find(p=>p.id===current.layout)?.name}}</span><div><button v-if="view==='slides'" class="btn shapes-trigger" @click="openShapes">+ Formes</button><button class="icon-btn" v-if="view==='slides'" :disabled="!studio.canUndo" @click="studio.undo" aria-label="Annuler" title="Annuler · Ctrl Z">↶</button><button class="icon-btn" v-if="view==='slides'" :disabled="!studio.canRedo" @click="studio.redo" aria-label="Rétablir" title="Rétablir · Ctrl Maj Z">↷</button><span class="resolution">{{resolution.width}} × {{resolution.height}}</span><span class="divider"></span><button class="icon-btn" @click="zoom=Math.max(60,zoom-10)" title="Dézoomer">−</button><span>{{zoom}} %</span><button class="icon-btn" @click="zoom=Math.min(100,zoom+10)" title="Zoomer">+</button></div></div>
    <div class="canvas-space" @pointerdown.self="deselect" :class="{'checker':view==='banners'}"><div ref="stage" @dragover="studio.dragImages" @drop="studio.dropImages" class="stage-wrap" :style="{width:presenting?'100%':zoom+'%', '--slide-ink':theme.ink}"><canvas ref="canvas" tabindex="0" :width="resolution.width" :height="resolution.height" @pointerdown="down" @pointermove="move" @pointerup="up" @pointercancel="up" @pointerleave="leave" @dblclick="doubleClick" @contextmenu="openContext" aria-label="Diapo : déplacer un bloc ou double-cliquer pour l’éditer"/><button v-for="h in !presenting&&!editing&&view==='slides'?handles:[]" :key="h.corner" class="resize-handle" :class="h.corner" :style="h.style" :aria-label="'Redimensionner : '+({nw:'haut gauche',n:'haut',ne:'haut droit',w:'gauche',e:'droite',sw:'bas gauche',s:'bas',se:'bas droit'})[h.corner]" @pointerdown.stop="resizeDown($event,h.corner)" @pointermove.stop="move" @pointerup.stop="up" @pointercancel.stop="up"/><button v-if="!presenting&&!editing&&view==='slides'&&selected" class="rotation-handle" :style="rotationHandle" aria-label="Tourner l’élément" title="Tourner · Maj : pas de 45°" @pointerdown.stop="rotateDown" @pointermove.stop="move" @pointerup.stop="up" @pointercancel.stop="up">↻</button>
    <InlineEditor v-if="editing" :key="current.id+editing" :style="editStyle" :text-style="selectedTextStyle" :font="studio.fontCss(position.font,selectedType)" :value="editedText" :code="selectedType==='code'" :label="editing==='title'?current.label:current.elements[editing]?.weight===700?current.elements[editing].label:undefined" :size="editSize" :scale="stageWidth/1920" @update="changeText" @label="editing==='title'?current.label=$event:current.elements[editing].label=$event" @close="closeEdit" @format="formatCode"/></div></div>
    <div class="canvas-bottom" v-if="!presenting"><button v-if="view==='slides'" class="distance-toggle" :class="{active:altHeld}" :aria-pressed="altHeld" @click="altHeld=!altHeld">Repères · Alt</button><span><MousePointer2 :size="14"/>{{view==='banners'?'Le fond sera transparent à l’export.':'Double-clic pour éditer · glisser pour déplacer.'}}</span><div v-if="view==='slides'"><button class="icon-btn" @click="navigate(-1)" :disabled="index===0" title="Diapo précédente"><ChevronLeft :size="16"/></button><span>{{index+1}} <span class="muted">/ {{slides.length}}</span></span><button class="icon-btn" @click="navigate(1)" :disabled="index===slides.length-1" title="Diapo suivante"><ChevronRight :size="16"/></button></div></div>
    <div class="speaker-note" v-if="panels.toolbar&&!presenting&&view==='slides'"><div class="note-icon"><Code2 :size="20"/></div><div><strong>Le contenu d’abord. Le design suit.</strong><p>Un thème commun, des compositions prêtes à l’emploi. Garde ton énergie pour Java.</p></div><span>⌘ studio</span></div>
    <div v-if="presenting&&countdown" class="record-countdown" role="status"><strong>{{countdown}}</strong><span>L’enregistrement commence dans {{countdown}} s</span><button class="btn" @click="startRecord">Annuler</button></div>
    <aside v-if="presenting" class="next-preview"><button @click="previewVisible=!previewVisible" :aria-expanded="previewVisible">Prochaine diapo {{previewVisible?'−':'+'}}</button><template v-if="previewVisible"><img v-if="slides[index+1]" :src="thumbs[slides[index+1].id]" alt="Aperçu de la prochaine diapo"><span v-else>Fin du diaporama</span><small>{{orders.length-step}} apparition(s) restante(s) · Espace</small></template></aside>
    <div class="present-controls" v-if="presenting">
      <button class="icon-btn" @click="exit" title="Quitter (Échap)"><X :size="19"/></button>
      <div class="direction-pad"><button class="icon-btn north" @click="goDirection('up')" :disabled="!canGo('up')" title="Diapo au-dessus (↑)"><ChevronUp :size="19"/></button><button class="icon-btn west" @click="goDirection('left')" :disabled="!canGo('left')" title="Diapo à gauche (←)"><ChevronLeft :size="19"/></button><button class="icon-btn south" @click="goDirection('down')" :disabled="!canGo('down')" title="Diapo en dessous (↓)"><ChevronDown :size="19"/></button><button class="icon-btn east" @click="goDirection('right')" :disabled="!canGo('right')" title="Diapo à droite (→)"><ChevronRight :size="19"/></button></div>
      <span class="presentation-status">{{index+1}} / {{slides.length}}<small>Étape {{step}} / {{orders.length}}</small></span>
      <button class="icon-btn" @click="retreat" :disabled="moving||(index===0&&step===0)" title="Revenir à l’étape précédente"><ChevronLeft :size="19"/></button>
      <button class="btn" @click="advance" :disabled="moving||(index===slides.length-1&&step===orders.length)" title="Espace ou Entrée">{{step<orders.length?'Révéler':'Suivant'}} · Espace<ChevronRight :size="16"/></button>
      <span class="divider"></span>
      <button :class="['icon-btn',{active:tool==='laser'}]" @click="tool='laser'" title="Laser · maintenir le clic gauche pour tracer"><MousePointer2 :size="19"/></button><button :class="['icon-btn',{active:tool==='pen'}]" @click="tool='pen'" title="Dessiner en maintenant la souris"><Pencil :size="19"/></button><input type="color" v-model="laser" aria-label="Couleur du pointeur"><input class="laser-range" type="range" min="4" max="30" v-model.number="laserSize" aria-label="Taille du pointeur"><button class="icon-btn" @click="clearAnnotations" title="Effacer les annotations"><RotateCcw :size="18"/></button>
      <button :disabled="finalizing" :class="['btn',recording?'danger':'primary']" @click="recording?stopRecord():startRecord()"><Square v-if="recording" :size="14"/><Circle v-else :size="14"/>{{recording?'Stop · '+Math.floor(elapsed/60)+':'+String(elapsed%60).padStart(2,'0'):countdown?'Annuler · '+countdown+' s':'Enregistrer'}}</button>
    </div>
   </section>
   <PropertiesPanel v-if="!presenting&&view==='slides'&&panels.properties" :studio="studio"/>
   <aside v-else-if="!presenting&&view==='banners'&&panels.properties" class="inspector"><button class="panel-resizer" @pointerdown="resizePanel($event,'inspectorWidth')" aria-label="Redimensionner les propriétés"></button><div class="panel-heading">Incrustation</div><div class="inspector-body"><label>Surtitre<input v-model="banner.subtitle"></label><label>Texte du bandeau<textarea v-model="banner.title" rows="4"></textarea></label><label v-if="banner.type==='video'">Indication complémentaire<input v-model="banner.note" maxlength="160" placeholder="Une autre vidéo sur la chaîne"></label><div class="section-label">THÈME</div><div class="swatches"><button v-for="t in themes" :key="t.id" :style="{background:t.accent}" :class="{chosen:themeId===t.id}" @click="themeId=t.id" :title="t.name" :aria-label="t.name"><Check v-if="themeId===t.id" :size="15"/></button></div><p class="field-help">Le thème est partagé avec ton diaporama.</p><button class="btn primary full" @click="png"><Download :size="16"/>Télécharger le bandeau</button></div>
    </aside>
  </div>
 </div><div class="toast" role="status" v-if="toast"><Check :size="17"/>{{toast}}</div>
</div>
<div v-if="themeEditor" class="modal-backdrop" @click.self="themeEditor=null"><form class="theme-editor" role="dialog" aria-modal="true" aria-label="Éditer un thème" @submit.prevent="saveTheme"><div class="export-heading"><h2>Ton identité visuelle</h2><button class="icon-btn" type="button" @click="themeEditor=null" aria-label="Fermer"><X :size="20"/></button></div><ThemePreview :theme="themeEditor"/><label>Nom<input type="text" v-model="themeEditor.name" maxlength="60" required></label><label>Description<input type="text" v-model="themeEditor.desc" maxlength="180"></label><div class="theme-colors"><label v-for="[key,name] in colorFields" :key="key">{{name}}<input type="color" v-model="themeEditor[key]"><input class="color-hex" type="text" :aria-label="name+' hexadécimal'" :value="themeEditor[key]" maxlength="7" @input="themeHex($event,key,false)" @change="themeHex($event,key)"></label></div><label class="checkbox-label"><input type="checkbox" v-model="themeEditor.light">Coloration syntaxique pour fond clair</label><div class="theme-page-actions"><button class="btn" type="button" @click="themeEditor=null">Annuler</button><button class="btn primary" type="submit">Sauvegarder le thème</button></div></form></div>
<ShapeGallery v-if="shapeGallery" :theme="theme" @close="shapeGallery=false" @choose="addShape"/>
<LayoutGallery v-if="gallery" :theme="theme" @close="gallery=false" @choose="chooseLayout" @memory="addMemory"/>
<div v-if="videoPreview&&lastExport?.video" class="export-backdrop" @click.self="videoPreview=false"><section class="export-dialog" role="dialog" aria-modal="true" aria-label="Votre enregistrement"><div class="export-heading"><div><strong>Ton enregistrement est prêt.</strong><p>{{lastExport.size}} Ko · WebM <span v-if="videoMeta">· {{videoMeta}}</span></p></div><button class="icon-btn" @click="videoPreview=false" title="Fermer l’aperçu"><X :size="20"/></button></div><video :src="lastExport.url" controls @loadedmetadata="videoMeta=$event.target.videoWidth+' × '+$event.target.videoHeight"/><a class="btn primary" :href="lastExport.url" :download="lastExport.name"><Download :size="16"/>Télécharger la vidéo</a></section></div>
<a v-if="lastExport&&!videoPreview&&!presenting" class="last-export" :href="lastExport.url" :download="lastExport.name"><Download :size="15"/>{{lastExport.name}} · {{lastExport.size}} Ko</a>
  <div v-if="formatOpen" class="modal-backdrop" @click.self="formatOpen=false"><section class="format-dialog" role="dialog" aria-modal="true" aria-label="Format du projet"><h2>Format du projet</h2><p>Diapos, bandeaux et vidéo utilisent ce format 16:9.</p><select v-model.number="formatWidth" aria-label="Résolution"><option :value="1280">HD · 1280 × 720</option><option :value="1920">Full HD · 1920 × 1080</option><option :value="2560">QHD · 2560 × 1440</option><option :value="3840">4K · 3840 × 2160</option></select><label>Largeur personnalisée<input type="number" v-model.number="formatWidth" min="640" max="3840" step="16"></label><p>Hauteur : {{formatWidth*9/16}} px</p><button class="btn" @click="formatOpen=false">Annuler</button><button class="btn primary" @click="applyFormat">Appliquer</button></section></div><div v-if="contextMenu" class="element-context" role="menu" :style="{left:contextMenu.x+'px',top:contextMenu.y+'px'}" @pointerdown.stop>
 <template v-if="contextMenu.element"><button v-if="!['image','shape'].includes(selectedType)" role="menuitem" @click="dismissContext();editSelected()">Éditer le contenu <span>Double-clic</span></button><button role="menuitem" @click="duplicateSelected">Dupliquer <span>Ctrl D</span></button><button role="menuitem" @click="removeBlock" >Supprimer</button><hr></template>
 <button role="menuitem" @click="dismissContext();addBlock('text')">Ajouter un texte</button><button role="menuitem" @click="dismissContext();addBlock('image')">Ajouter une image</button><button role="menuitem" @click="dismissContext();addBlock('code')">Ajouter du code</button><button role="menuitem" @click="openShapes">Ajouter une forme</button>
</div></template>
