<script setup>
import { PanelsTopLeft, Clapperboard, Palette, Plus, Play, Download, ChevronLeft, ChevronRight, ChevronDown, ChevronUp, Copy, Trash2, Check, Code2, MousePointer2, RotateCcw, Upload, X, Circle, Square, Pencil, Monitor, Save, GripVertical, ImagePlus, Type, LayoutGrid } from 'lucide-vue-next';
import { useStudio } from './useStudio.js';
import { themes, presets, visibleBlocks, blockLabel } from './model.js';
import InlineEditor from './components/InlineEditor.vue';
import DeckCanvas from './components/DeckCanvas.vue';
import LayoutGallery from './components/LayoutGallery.vue';
const { workspace, listDrag, listTarget, selectedType, editedText, exitLabel, changeText, addBlock, removeBlock, uploadImage, reorder, listDown, moveGrid, slides, project, themeId, frame, banner, index, view, tab, selected, presenting, canvas, stage, stageWidth, toast, saved, zoom, recording, elapsed, laser, laserSize, tool, lastExport, videoPreview, videoMeta, finalizing, gallery, editing, formatting, thumbs, step, transitionMs, moving, gridDraft, current, theme, position, orders, editStyle, add, chooseLayout, addMemory, applyPreset, duplicate, remove, applyGrid, setPosition, updateFragment, formatCode, exportProject, importProject, png, startPresentation, exit, startRecord, stopRecord, navigate, advance, retreat, goDirection, canGo, chooseSlide, down, move, up, leave, doubleClick, closeEdit, editSelected, clearAnnotations } = useStudio();
</script>

<template>
<div class="studio" :class="{presenting}">
 <aside class="rail" v-if="!presenting">
  <a class="brand" href="#" @click.prevent="view='slides'" aria-label="Frame accueil"><span class="brand-icon">f</span><span>frame<span class="brand-dot">.</span></span></a>
  <div class="workspace-label">TON ATELIER</div>
  <button :class="{active:view==='slides'}" @click="view='slides'"><PanelsTopLeft :size="19"/>Diaporamas</button>
  <button :class="{active:view==='banners'}" @click="view='banners'"><Clapperboard :size="19"/>Incrustations</button>
  <button :class="{active:view==='themes'}" @click="view='themes'"><Palette :size="19"/>Thèmes</button>
  <div class="rail-bottom"><div class="personal-avatar">K</div><div>Mon espace<span>Studio personnel</span></div><span class="version">v1</span></div>
 </aside>
 <div class="main-shell">
  <header v-if="!presenting"><div class="breadcrumb">Mon studio <span>/</span> {{view==='slides'?'Diaporamas':view==='banners'?'Incrustations':'Thèmes'}}</div><div class="header-right"><span class="save-state"><Check :size="14" v-if="saved"/>{{saved?'Sauvegardé sur cet appareil':'Sauvegarde…'}}</span><label class="icon-btn" title="Importer un projet"><Upload :size="17"/><input type="file" accept="application/json" hidden @change="importProject"></label><button class="icon-btn" title="Exporter le projet JSON" @click="exportProject"><Save :size="17"/></button><span class="avatar">K</span></div></header>
  <div class="project-bar" v-if="!presenting"><div><div class="eyebrow">{{view==='banners'?'HABILLAGE VIDÉO':view==='themes'?'IDENTITÉ VISUELLE':'DIAPORAMA'}}</div><input v-model="project" class="project-name" aria-label="Nom du projet"><span class="project-meta" v-if="view==='slides'">{{slides.length}} diapos <span>·</span> 16:9 <span>·</span> 1920 × 1080</span></div><div class="project-actions"><div class="workspace-switch" v-if="view==='slides'"><button :class="{active:workspace==='canvas'}" @click="workspace='canvas';closeEdit()"><LayoutGrid :size="15"/>Canvas</button><button :class="{active:workspace==='editor'}" @click="workspace='editor'"><Monitor :size="15"/>Éditer</button></div><button class="btn" @click="png" v-if="view!=='themes'"><Download :size="16"/>{{view==='banners'?'Exporter le PNG':'Exporter la diapo'}}</button><button class="btn primary" @click="startPresentation()"><Play :size="16"/>Présenter</button></div></div>
  <template v-if="view==='themes'">
   <section class="theme-page"><h2>Une identité. Toutes tes créations.</h2><p>Le thème s’applique à toutes les diapos et à tes incrustations.</p><div class="theme-grid"><button v-for="t in themes" :key="t.id" :class="['theme-card',{chosen:themeId===t.id}]" @click="themeId=t.id"><div class="theme-example" :style="{background:t.bg,color:t.ink}"><span :style="{color:t.accent}">JAVA / SOUS LE CAPOT</span><strong>Comprendre.<br>Construire.</strong><div :style="{background:t.panel,color:t.accent}">public class HelloWorld { }</div></div><div class="theme-caption">{{t.name}}<Check v-if="themeId===t.id" :size="18"/></div></button></div></section>
  </template>
  <div class="editor" v-else>
   <aside class="slides-panel" v-if="view==='slides'&&!presenting&&workspace==='editor'"><div class="panel-heading">Diapos <span>{{slides.length}}</span><button class="icon-btn" @click="add" title="Ajouter une diapo"><Plus :size="17"/></button></div><div class="slide-list"><div v-for="(s,n) in slides" :key="s.id" :data-slide-index="n" :class="['slide-row',{'drop-target':listDrag!==null&&listTarget===n,sorting:listDrag===n}]"><button class="slide-grip" @pointerdown="listDown($event,n)" @keydown.up.prevent="reorder(n,Math.max(0,n-1))" @keydown.down.prevent="reorder(n,Math.min(slides.length-1,n+1))" :aria-label="'Déplacer la diapo '+(n+1)" title="Glisser pour réordonner · flèches ↑ ↓ au clavier"><GripVertical :size="15"/></button><button :class="['slide-item',{chosen:index===n}]" @pointerdown="listDown($event,n)" @click="chooseSlide(n)"><div class="slide-thumb"><img :src="thumbs[s.id]" alt="" draggable="false"><span class="slide-number">{{String(n+1).padStart(2,'0')}}</span></div><span class="slide-title">{{s.title.replaceAll('\n',' ')}}</span></button></div></div><button class="add-slide" @click="add"><Plus :size="16"/>Ajouter une diapo</button><div class="slide-actions"><button class="icon-btn" @click="duplicate" title="Dupliquer"><Copy :size="16"/></button><button class="icon-btn" @click="remove" :disabled="slides.length===1" title="Supprimer la diapo"><Trash2 :size="16"/></button></div></aside>
   <aside class="slides-panel banner-presets" v-if="view==='banners'"><div class="panel-heading">Formats</div><button v-for="b in [{id:'lower',name:'Bandeau de titre',sub:'En bas de la vidéo'},{id:'chapter',name:'Titre de chapitre',sub:'Au centre de la vidéo'},{id:'tip',name:'À retenir',sub:'Dans le coin supérieur'}]" :key="b.id" :class="['format-card',{chosen:banner.type===b.id}]" @click="banner.type=b.id"><Clapperboard :size="26"/><strong>{{b.name}}</strong><span>{{b.sub}}</span></button><div class="format-note">PNG transparent<br>1920 × 1080</div></aside>
   <DeckCanvas v-if="view==='slides'&&!presenting&&workspace==='canvas'" :slides="slides" :thumbs="thumbs" :index="index" @select="chooseSlide" @edit="chooseSlide($event);workspace='editor'" @move="moveGrid" @add="add"/>
   <section class="work-area" v-else>
    <div class="canvas-toolbar" v-if="!presenting"><span><Monitor :size="15"/>{{view==='banners'?'Aperçu de l’incrustation':presets.find(p=>p.id===current.layout)?.name}}</span><div><span class="resolution">FULL HD</span><span class="divider"></span><button class="icon-btn" @click="zoom=Math.max(60,zoom-10)" title="Dézoomer">−</button><span>{{zoom}} %</span><button class="icon-btn" @click="zoom=Math.min(100,zoom+10)" title="Zoomer">+</button></div></div>
    <div class="canvas-space" :class="{'checker':view==='banners'}"><div ref="stage" class="stage-wrap" :style="{width:presenting?'100%':zoom+'%', '--slide-ink':theme.ink}"><canvas ref="canvas" width="1920" height="1080" @pointerdown="down" @pointermove="move" @pointerup="up" @pointercancel="up" @pointerleave="leave" @dblclick="doubleClick" aria-label="Diapo : déplacer un bloc ou double-cliquer pour l’éditer"/><InlineEditor v-if="editing" :key="current.id+editing" :style="editStyle" :value="editedText" :code="editing==='code'" :label="editing==='title'?current.label:undefined" :size="position.size" :scale="stageWidth/1920" @update="changeText" @label="current.label=$event" @close="closeEdit" @format="formatCode"/></div></div>
    <div class="canvas-bottom" v-if="!presenting"><span><MousePointer2 :size="14"/>{{view==='banners'?'Le fond sera transparent à l’export.':'Double-clic pour éditer · glisser pour déplacer.'}}</span><div v-if="view==='slides'"><button class="icon-btn" @click="navigate(-1)" :disabled="index===0" title="Diapo précédente"><ChevronLeft :size="16"/></button><span>{{index+1}} <span class="muted">/ {{slides.length}}</span></span><button class="icon-btn" @click="navigate(1)" :disabled="index===slides.length-1" title="Diapo suivante"><ChevronRight :size="16"/></button></div></div>
    <div class="speaker-note" v-if="!presenting&&view==='slides'"><div class="note-icon"><Code2 :size="20"/></div><div><strong>Le contenu d’abord. Le design suit.</strong><p>Un thème commun, des compositions prêtes à l’emploi. Garde ton énergie pour Java.</p></div><span>⌘ studio</span></div>
    <div class="present-controls" v-if="presenting">
      <button class="icon-btn" @click="exit" title="Quitter (Échap)"><X :size="19"/></button>
      <div class="direction-pad"><button class="icon-btn north" @click="goDirection('up')" :disabled="!canGo('up')" title="Diapo au-dessus (↑)"><ChevronUp :size="19"/></button><button class="icon-btn west" @click="goDirection('left')" :disabled="!canGo('left')" title="Diapo à gauche (←)"><ChevronLeft :size="19"/></button><button class="icon-btn south" @click="goDirection('down')" :disabled="!canGo('down')" title="Diapo en dessous (↓)"><ChevronDown :size="19"/></button><button class="icon-btn east" @click="goDirection('right')" :disabled="!canGo('right')" title="Diapo à droite (→)"><ChevronRight :size="19"/></button></div>
      <span class="presentation-status">{{index+1}} / {{slides.length}}<small>Étape {{step}} / {{orders.length}}</small></span>
      <button class="icon-btn" @click="retreat" :disabled="moving||(index===0&&step===0)" title="Revenir à l’étape précédente"><ChevronLeft :size="19"/></button>
      <button class="btn" @click="advance" :disabled="moving||(index===slides.length-1&&step===orders.length)" title="Espace ou clic sur la diapo">{{step<orders.length?'Révéler':'Suivant'}}<ChevronRight :size="16"/></button>
      <span class="divider"></span>
      <button :class="['icon-btn',{active:tool==='laser'}]" @click="tool='laser'" title="Laser"><MousePointer2 :size="19"/></button><button :class="['icon-btn',{active:tool==='pen'}]" @click="tool='pen'" title="Dessiner en maintenant la souris"><Pencil :size="19"/></button><input type="color" v-model="laser" aria-label="Couleur du pointeur"><input class="laser-range" type="range" min="4" max="30" v-model.number="laserSize" aria-label="Taille du pointeur"><button class="icon-btn" @click="clearAnnotations" title="Effacer les annotations"><RotateCcw :size="18"/></button>
      <button :disabled="finalizing" :class="['btn',recording?'danger':'primary']" @click="recording?stopRecord():startRecord()"><Square v-if="recording" :size="14"/><Circle v-else :size="14"/>{{recording?'Stop · '+Math.floor(elapsed/60)+':'+String(elapsed%60).padStart(2,'0'):'Enregistrer'}}</button>
    </div>
   </section>
   <aside class="inspector" v-if="!presenting">
    <div class="inspector-tabs" v-if="view==='slides'"><button :class="{active:tab==='layout'}" @click="tab='layout'">Composition</button><button :class="{active:tab==='animation'}" @click="tab='animation'">Animation</button></div><div class="panel-heading" v-else>Personnaliser</div>
    <div class="inspector-body" v-if="view==='banners'"><label>Surtitre<input v-model="banner.subtitle"></label><label>Texte du bandeau<textarea v-model="banner.title" rows="4"></textarea></label><div class="section-label">THÈME</div><div class="swatches"><button v-for="t in themes" :key="t.id" :style="{background:t.accent}" :class="{chosen:themeId===t.id}" @click="themeId=t.id" :title="t.name" :aria-label="t.name"><Check v-if="themeId===t.id" :size="15"/></button></div><p class="field-help">Le thème est partagé avec ton diaporama.</p><button class="btn primary full" @click="png"><Download :size="16"/>Télécharger le bandeau</button></div>
    <div class="inspector-body" v-else>
      <button class="btn full preview-slide" @click="startPresentation(false)"><Play :size="14"/>Tester cette diapo</button><div class="section-label spaced">DÉPART DE CETTE DIAPO</div>
      <div class="slide-exit-preview"><span>Diapo {{index+1}}</span><strong>{{exitLabel}}</strong><small>{{index===slides.length-1?'Dernière diapo':`Puis diapo ${index+2}`}}</small></div>
      <label>Sortie vers<select v-model="current.exitDirection" aria-label="Direction de sortie"><option value="auto">Automatique · position sur le canvas</option><option value="left">← Gauche</option><option value="right">→ Droite</option><option value="up">↑ Haut</option><option value="down">↓ Bas</option></select></label>
      <div class="section-label spaced">ÉLÉMENTS DE LA DIAPO</div>
      <div class="block-add"><button class="btn" @click="workspace='editor';addBlock('text')"><Type :size="15"/>Texte</button><button class="btn" @click="workspace='editor';addBlock('image')"><ImagePlus :size="15"/>Image</button></div>
      <label>Bloc<select v-model="selected"><option v-for="k in visibleBlocks(current)" :key="k" :value="k">{{blockLabel(current,k)}}</option></select></label>
      <button v-if="selectedType!=='image'" class="btn full edit-block" @click="workspace='editor';editSelected()"><Pencil :size="15"/>Éditer sur la diapo</button>
      <template v-if="selectedType==='image'"><label class="image-upload"><ImagePlus :size="18"/>{{current.elements[selected].src?'Remplacer l’image':'Importer une image'}}<input type="file" accept="image/png,image/jpeg,image/webp" @change="uploadImage"></label><label>Ajustement<select v-model="current.elements[selected].fit"><option value="contain">Image entière</option><option value="cover">Remplir et recadrer</option></select></label><p class="field-help">PNG, JPEG ou WebP · intégrée à la sauvegarde JSON.</p></template>
      <button v-if="current.elements[selected]" class="delete-block" @click="removeBlock"><Trash2 :size="13"/>Supprimer cet élément</button>
      <p class="field-help">Double-clique directement sur le texte ou le code pour le modifier.</p>
      <template v-if="tab==='layout'">
        <div class="section-label spaced">DISPOSITION</div>
        <select class="layout-select" v-model="current.layout" @change="applyPreset(current.layout)" aria-label="Disposition de la diapo"><option v-for="p in presets" :key="p.id" :value="p.id">{{p.name}}</option></select>
        <div class="section-label spaced">POSITION ET TYPOGRAPHIE</div>
        <div class="position-grid"><label v-for="(label,key) in selectedType==='image'?{x:'X',y:'Y',w:'Largeur',h:'Hauteur'}:{x:'X',y:'Y',w:'Largeur',size:'Taille du texte'}" :key="key">{{label}}<input type="number" :value="position[key]" :min="key==='size'?10:key==='w'?80:0" :max="key==='size'?260:key==='y'||key==='h'?1080:1920" @change="setPosition(key,$event)"></label></div>
        <div class="section-label spaced">HABILLAGE FACULTATIF</div>
        <label class="checkbox-label"><input type="checkbox" v-model="frame.header">En-tête de diapo</label><label class="checkbox-label"><input type="checkbox" v-model="frame.footer">Pied de diapo</label>
        <div class="section-label spaced">THÈME GLOBAL</div><div class="swatches"><button v-for="t in themes" :key="t.id" :style="{background:t.accent}" :class="{chosen:themeId===t.id}" @click="themeId=t.id" :title="t.name" :aria-label="t.name"><Check v-if="themeId===t.id" :size="15"/></button></div>
      </template>
      <template v-else>
        <label>Ordre d’apparition<input type="number" min="0" max="20" :value="current.fragments[selected].order" @change="updateFragment"></label>
        <p class="field-help">0 : visible au départ. Les blocs de même ordre apparaissent ensemble au clic ou avec Espace.</p>
        <label>Animation<select v-model="current.fragments[selected].animation"><option value="fade">Fondu</option><option value="up">Montée douce</option><option value="zoom">Zoom léger</option><option value="none">Immédiate</option></select></label>
        <div class="section-label spaced">SÉQUENCE AU CLIC</div><div class="fragment-list"><label v-for="k in visibleBlocks(current)" :key="k"><span>{{blockLabel(current,k)}}</span><input type="number" min="0" max="20" v-model.number="current.fragments[k].order" :aria-label="'Ordre de '+blockLabel(current,k)" @change="current.fragments[k].order=Math.max(0,Math.min(20,Math.round(Number(current.fragments[k].order)||0)))"></label></div>
        <p class="field-help">Trois textes avec les ordres 1, 2, 3 : trois clics, puis la diapo suivante.</p>
        <div class="section-label spaced">POSITION SUR LE CANVAS</div>
        <div class="position-grid"><label>Colonne<input type="number" min="-10000" max="10000" v-model.number="gridDraft.x"></label><label>Ligne<input type="number" min="-10000" max="10000" v-model.number="gridDraft.y"></label></div><button class="btn full" @click="applyGrid">Appliquer la position</button>
        <p class="field-help">La colonne augmente vers la droite ; la ligne augmente vers le bas.</p>
        <label>Durée de transition<select v-model.number="transitionMs"><option :value="0">Immédiate</option><option :value="350">Rapide · 350 ms</option><option :value="650">Fluide · 650 ms</option><option :value="1000">Lente · 1 seconde</option></select></label>

        <p class="field-help">En présentation : flèches pour le parcours, Espace pour les apparitions et la suite.</p>
      </template>
      <p class="field-help format-state" v-if="formatting">Formatage Java en cours…</p>
    </div>
   </aside>
  </div>
 </div><div class="toast" role="status" v-if="toast"><Check :size="17"/>{{toast}}</div>
</div>
<LayoutGallery v-if="gallery" :theme="theme" @close="gallery=false" @choose="chooseLayout" @memory="addMemory"/>
<div v-if="videoPreview&&lastExport?.video" class="export-backdrop" @click.self="videoPreview=false"><section class="export-dialog" role="dialog" aria-modal="true" aria-label="Votre enregistrement"><div class="export-heading"><div><strong>Ton enregistrement est prêt.</strong><p>{{lastExport.size}} Ko · WebM <span v-if="videoMeta">· {{videoMeta}}</span></p></div><button class="icon-btn" @click="videoPreview=false" title="Fermer l’aperçu"><X :size="20"/></button></div><video :src="lastExport.url" controls @loadedmetadata="videoMeta=$event.target.videoWidth+' × '+$event.target.videoHeight"/><a class="btn primary" :href="lastExport.url" :download="lastExport.name"><Download :size="16"/>Télécharger la vidéo</a></section></div>
<a v-if="lastExport&&!videoPreview&&!presenting" class="last-export" :href="lastExport.url" :download="lastExport.name"><Download :size="15"/>{{lastExport.name}} · {{lastExport.size}} Ko</a>
</template>
