import {fontCss} from './fonts.js';
import {boundColor,validColorRole} from './colors.js';
const bounded=(v,min,max,fallback)=>Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):fallback;
export function normalizeBits(raw={}){const result={type:'bits',custom:raw.custom!==false,template:raw.template===true,name:String(raw.name||'Octets et bits').slice(0,100),value:String(raw.value??'151').slice(0,80),bytes:Math.round(bounded(raw.bytes,1,8,1)),signed:raw.signed===true,bytesPerRow:Math.round(bounded(raw.bytesPerRow,1,8,2)),showLabels:raw.showLabels!==false,showValue:raw.showValue!==false,showWeights:raw.showWeights===true,radius:bounded(raw.radius,0,24,8)};for(const [field,role,color] of [['one','accent','#ff583c'],['zero','panel','#f5f4f0'],['border','accent','#ff8d2d'],['oneText','bg','#ffffff'],['zeroText','ink','#434750']]){result[field]=/^#[\da-f]{6}$/i.test(raw[field])?raw[field]:color;result[field+'Role']=Object.hasOwn(raw,field+'Role')?validColorRole(raw[field+'Role']):role;}return result;}
export function bitValue(element){const width=element.bytes*8,bits=BigInt(width),min=element.signed?-(1n<<(bits-1n)):0n,max=(1n<<(element.signed?bits-1n:bits))-1n;const fail=error=>({error,min:String(min),max:String(max),binary:null,octets:[]});if(!/^[+-]?\d{1,79}$/.test(String(element.value).trim()))return fail('Saisis un nombre entier décimal.');const value=BigInt(element.value.trim());if(value<min||value>max)return fail(`Valeur hors plage : ${min} à ${max}.`);const binary=BigInt.asUintN(width,value).toString(2).padStart(width,'0');return {error:null,value:String(value),min:String(min),max:String(max),binary,octets:binary.match(/.{8}/g)};}
export function bitLayout(e,p){const columns=Math.min(e.bytes,e.bytesPerRow),rows=Math.ceil(e.bytes/columns),header=e.showValue?48:0,footer=e.showLabels?26:0,weight=e.showWeights?30:0,pad=12,gap=20,width=(p.w-pad*2-gap*(columns-1))/columns,height=((p.h||220)-header-pad*2-gap*(rows-1))/rows;return {columns,rows,header,footer,weight,pad,gap,width:Math.max(1,width),height:Math.max(1,height)};}
export function drawBits(ctx,e,p,theme){const value=bitValue(e),l=bitLayout(e,p),h=p.h||220;ctx.save();ctx.beginPath();ctx.rect(p.x,p.y,p.w,h);ctx.clip();ctx.textAlign='left';ctx.textBaseline='middle';ctx.letterSpacing='0px';const print=(text,x,y,size,color,weight=400)=>{ctx.font=`${weight} ${size}px ${fontCss('inter')}`;ctx.fillStyle=color;ctx.fillText(text,x,y);};if(value.error){print('Valeur hors plage',p.x+12,p.y+Math.min(h/2,40),Math.min(28,h/3),theme.ink);ctx.restore();return;}if(e.showValue)print(`${value.value}  ·  ${e.bytes} octet${e.bytes>1?'s':''} / ${e.bytes*8} bits`,p.x+12,p.y+22,Math.min(28,p.w/25),theme.ink,700);
value.octets.forEach((octet,index)=>{const x=p.x+l.pad+(index%l.columns)*(l.width+l.gap),y=p.y+l.header+l.pad+Math.floor(index/l.columns)*(l.height+l.gap),cellHeight=Math.max(1,l.height-l.footer-l.weight),outerPad=Math.min(8,l.width/40,cellHeight/8),gap=Math.min(6,l.width/60),cw=Math.max(1,(l.width-outerPad*2-gap*7)/8),ch=Math.max(1,cellHeight-outerPad*2),radius=Math.min(e.radius,cw/4,ch/4);ctx.beginPath();ctx.roundRect(x,y,l.width,cellHeight,Math.min(radius+4,cellHeight/4));ctx.strokeStyle=boundColor(e,'border',theme);ctx.lineWidth=2;ctx.stroke();[...octet].forEach((bit,n)=>{const bx=x+outerPad+n*(cw+gap),by=y+outerPad;ctx.beginPath();ctx.roundRect(bx,by,cw,ch,radius);ctx.fillStyle=boundColor(e,bit==='1'?'one':'zero',theme);ctx.fill();ctx.strokeStyle=boundColor(e,'border',theme);ctx.lineWidth=1.5;ctx.stroke();ctx.textAlign='center';print(bit,bx+cw/2,by+ch/2,Math.min(38,cw*.65,ch*.65),boundColor(e,bit==='1'?'oneText':'zeroText',theme));if(e.showWeights)print(String(2**(7-n)),bx+cw/2,y+cellHeight+15,Math.min(22,cw*.4),theme.muted);});ctx.textAlign='left';if(e.showLabels)print(`Octet ${index+1} · ${parseInt(octet,2)}`,x,y+cellHeight+l.weight+15,Math.min(22,l.width/15),theme.muted);});ctx.restore();}
export function applyBitsPreset(e,id){if(id==='reference')Object.assign(e,{one:'#ff583c',zero:'#f5f4f0',border:'#ff8d2d',oneText:'#ffffff',zeroText:'#434750',oneRole:null,zeroRole:null,borderRole:null,oneTextRole:null,zeroTextRole:null});else Object.assign(e,{oneRole:'accent',zeroRole:'panel',borderRole:'accent',oneTextRole:'bg',zeroTextRole:'ink'});}
