// Each state owns its editable scene; changing it never mutates an earlier step.
const sceneFields=['id','grid','exitDirection','title','body','code','label','codeTitle','notes','layout','designVersion','positions','fragments','elements','blockKeys','blockNames','groups','hiddenKeys','emphasisKeys'];
export const MAX_PEDAGOGICAL_STEPS=20;
export function captureScene(slide){return JSON.parse(JSON.stringify(Object.fromEntries(sceneFields.filter(k=>slide[k]!==undefined).map(k=>[k,slide[k]]))));}
export function sceneAt(slide,n=0){const scene=n>0?slide.pedagogicalSteps?.[n-1]?.scene:null;return scene?{...slide,...scene,pedagogicalSteps:undefined}:slide;}
export function normalizeSteps(raw,base,normalize){if(!Array.isArray(raw))return [];const ids=new Set();return raw.slice(0,MAX_PEDAGOGICAL_STEPS).flatMap((item,n)=>{if(!item?.scene||typeof item.scene!=='object')return [];try{const scene=normalize({...base,...item.scene,id:base.id,grid:base.grid,exitDirection:base.exitDirection,pedagogicalSteps:[]});let id=typeof item.id==='string'?item.id.slice(0,100):crypto.randomUUID();if(ids.has(id))id=crypto.randomUUID();ids.add(id);return [{id,name:String(item.name||`Étape ${n+1}`).slice(0,100),scene:captureScene(scene)}];}catch{return [];}});}
export function presentationSequence(slide,orders){const sequence=[];for(let n=0;n<=(slide.pedagogicalSteps?.length||0);n++){const scene=sceneAt(slide,n);sequence.push({scene:n,order:0,name:n?slide.pedagogicalSteps[n-1].name:'État initial'});for(const order of orders(scene))sequence.push({scene:n,order,name:`${n?slide.pedagogicalSteps[n-1].name:'État initial'} · apparition ${order}`});}return sequence;}
export function addPedagogicalStep(slide,source=0){slide.pedagogicalSteps||=[];if(slide.pedagogicalSteps.length>=MAX_PEDAGOGICAL_STEPS)return null;const scene=captureScene(sceneAt(slide,source));for(const f of Object.values(scene.fragments||{}))f.order=0;const item={id:crypto.randomUUID(),name:`Étape ${slide.pedagogicalSteps.length+1}`,scene};slide.pedagogicalSteps.splice(source,0,item);return source+1;}
export function movePedagogicalStep(slide,n,delta){const target=n-1+delta;if(n<1||target<0||target>=slide.pedagogicalSteps.length)return n;const [item]=slide.pedagogicalSteps.splice(n-1,1);slide.pedagogicalSteps.splice(target,0,item);return target+1;}

export function allScenes(slides){return slides.flatMap(s=>[s,...(s.pedagogicalSteps||[]).map(item=>item.scene)]);}
