export function audienceMessage(event,source,origin,session){return event.origin===origin&&event.source===source&&event.data?.session===session;}
export class AudienceFrames{
  constructor({source,origin,session,paint,ack}){Object.assign(this,{source,origin,session,paint,ack});this.sequence=-1;}
  receive(event){if(!audienceMessage(event,this.source,this.origin,this.session)||event.data.type!=='frame-audience-frame')return false;const {bitmap,sequence}=event.data;if(!bitmap)return false;try{if(!Number.isSafeInteger(sequence)||sequence<=this.sequence)return false;this.paint(bitmap);this.sequence=sequence;this.ack?.(sequence);return true;}finally{bitmap.close();}}
}
export class PresenterSession{
  constructor({host,bitmap,notify,command,status,now=()=>performance.now(),schedule=(callback,ms)=>setTimeout(callback,ms),cancel=id=>clearTimeout(id)}){Object.assign(this,{host,bitmap,notify,command,status,now,schedule,cancel});this.child=null;this.token='';this.ready=false;this.busy=false;this.lastFrame=-Infinity;this.sequence=0;this.generation=0;this.pending=null;this.pendingTimer=null;this.receivedFrames=0;}
  receive(event){if(!audienceMessage(event,this.child,this.host.location.origin,this.token))return;const type=event.data.type;if(type==='frame-audience-ready'){this.ready=true;this.status(true,true);this.command('ready');}else if(type==='frame-audience-painted'){this.receivedFrames++;}else if(type==='frame-audience-command'&&['advance','retreat','exit'].includes(event.data.action))this.command(event.data.action);}
  open(){if(this.child&&!this.child.closed){this.child.focus();return true;}this.token=crypto.randomUUID();const url=new URL(this.host.location.href);url.search='';url.hash='';url.searchParams.set('frameAudience',this.token);this.child=this.host.open(url.href,'frame-public-'+this.token,'popup,width=1280,height=720');if(!this.child){this.notify('Le navigateur bloque la fenêtre Public. Autorise les fenêtres contextuelles pour Frame, puis réessaie.');return false;}this.ready=false;this.status(true,false);this.generation++;return true;}
  close(){this.generation++;this.cancel(this.pendingTimer);this.pendingTimer=null;this.pending=null;this.child?.close();this.child=null;this.ready=false;this.status(false,false);}
  heartbeat(){if(this.child?.closed){this.child=null;this.ready=false;this.status(false,false);this.notify('La fenêtre Public a été fermée. Tu peux la rouvrir depuis la console.');}else if(this.child&&this.ready)this.child.postMessage({type:'frame-audience-heartbeat',session:this.token},this.host.location.origin);}
  async mirror(canvas,now=this.now()){if(!this.ready||!this.child||this.child.closed)return;this.pending=canvas;if(this.busy)return;if(now-this.lastFrame<1000/30){if(!this.pendingTimer)this.pendingTimer=this.schedule(()=>{this.pendingTimer=null;if(this.pending)this.mirror(this.pending);},Math.ceil(1000/30-(now-this.lastFrame)));return;}this.pending=null;this.lastFrame=now;this.busy=true;const target=this.child,session=this.token,version=this.generation;let bitmap;try{bitmap=await this.bitmap(canvas);if(version!==this.generation||target.closed){bitmap.close();return;}target.postMessage({type:'frame-audience-frame',session,sequence:++this.sequence,bitmap},this.host.location.origin,[bitmap]);}catch{bitmap?.close();}finally{this.busy=false;if(this.pending)this.mirror(this.pending);}}
}
