import { fonts, normalizeFont } from './fonts.js';
export const weightNames={100:'Très fin',200:'Fin',300:'Léger',400:'Normal',500:'Moyen',600:'Demi-gras',700:'Gras',800:'Extra-gras',900:'Noir'};
export function fontWeights(id,type='text'){return fonts.find(f=>f.id===normalizeFont(id,type)).weights||[400,700];}
export function normalizeTextStyle(raw={},font,type='text',heading=false){
 const weights=fontWeights(font,type),requested=Number(raw?.weight),weight=weights.reduce((a,b)=>Math.abs(b-(Number.isFinite(requested)?requested:heading?700:400))<Math.abs(a-(Number.isFinite(requested)?requested:heading?700:400))?b:a);
 return {weight,italic:raw?.italic===true,underline:raw?.underline===true,strike:raw?.strike===true,highlight:raw?.highlight===true,highlightColor:/^#[\da-f]{6}$/i.test(raw?.highlightColor)?raw.highlightColor:'#ffe066',highlightOpacity:Number.isFinite(Number(raw?.highlightOpacity))?Math.max(0,Math.min(100,Number(raw.highlightOpacity))):35};
}
export function getTextStyle(s,key){const p=s.positions[key]||{};return normalizeTextStyle(p.textStyle,p.font,key==='code'||s.elements?.[key]?.type==='code'?'code':'text',key==='title'||s.elements?.[key]?.weight===700);}
export function styleFont(size,font,style){return `${style.italic?'italic ':''}${style.weight} ${size}px ${font}`;}
export function textMarkCss(style){return {textDecorationLine:[style.underline?'underline':'',style.strike?'line-through':''].filter(Boolean).join(' ')||'none',backgroundColor:style.highlight?style.highlightColor+Math.round(style.highlightOpacity/100*255).toString(16).padStart(2,'0'):'transparent',boxDecorationBreak:'clone',WebkitBoxDecorationBreak:'clone'};}
export function usedFontFaces(slides){const requests=new Map();for(const s of slides)for(const [key,p] of Object.entries(s.positions)){if(['image','shape'].includes(s.elements?.[key]?.type))continue;const type=key==='code'||s.elements?.[key]?.type==='code'?'code':'text',id=normalizeFont(p.font,type),f=fonts.find(f=>f.id===id),style=getTextStyle(s,key);if(f.local)continue;const request={id,weight:style.weight,italic:style.italic&&f.italic===true};requests.set(JSON.stringify(request),request);}return [...requests.values()].sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));}
