<script setup>
import {reactive,ref,onMounted,onUnmounted} from 'vue';
import {Play,LayoutGrid,Monitor,Check,Plus} from 'lucide-vue-next';
const props=defineProps({studio:Object});const s=reactive(props.studio),active=ref(null),root=ref(null);
function toggle(menu){active.value=active.value===menu?null:menu;}
function act(callback){active.value=null;callback();}
function add(type){act(()=>{s.workspace='editor';s.addBlock(type);});}
function outside(event){if(!root.value?.contains(event.target))active.value=null;}
onMounted(()=>document.addEventListener('pointerdown',outside));onUnmounted(()=>document.removeEventListener('pointerdown',outside));
</script>
<template><header ref="root" class="app-header" @keydown.esc.stop="active=null">
 <div class="app-header-left"><a class="brand header-brand" href="#" @click.prevent="s.view='slides'" aria-label="Frame accueil"><span class="brand-icon">f</span><span class="brand-name">frame<span class="brand-dot">.</span></span></a><nav class="app-menus" aria-label="Menus de l’application"><div v-for="menu in ['Fichier','Affichage','Projet','Insérer']" :key="menu" class="app-menu" v-show="menu!=='Insérer'||s.view!=='themes'"><button class="app-menu-trigger" :aria-expanded="active===menu" @click="toggle(menu)">{{menu}}</button><div v-if="active===menu" class="app-menu-popover" :aria-label="'Menu '+menu">
 <template v-if="menu==='Fichier'"><button v-if="s.openSupported" :disabled="s.fileBusy" @click="act(()=>s.openProject())">Ouvrir un fichier lié</button><label class="menu-file">Importer un document JSON<input type="file" accept="application/json" @change="s.importProject($event);active=null"></label><hr><button :disabled="s.fileBusy" @click="act(()=>s.saveProject(false))">Enregistrer <kbd>Ctrl S</kbd></button><button :disabled="s.fileBusy" @click="act(()=>s.saveProject(true))">Enregistrer sous… <kbd>Ctrl Maj S</kbd></button><button @click="act(()=>s.exportProject())">{{s.documentScope==='banners'?'Exporter l’incrustation JSON':'Exporter le diaporama JSON'}}</button><button v-if="s.view!=='themes'" @click="act(()=>s.png())">{{s.view==='banners'?'Exporter le PNG transparent':'Exporter la diapo PNG'}}</button><button v-if="s.view==='banners'" @click="act(()=>s.openOverlayVideo())">Exporter une incrustation animée…</button><small v-if="s.fileName">{{s.fileName}}{{s.fileDirty?' · modifié':''}}</small></template>
 <template v-else-if="menu==='Affichage'"><label v-for="[key,name] in [['rail','Navigation latérale'],['properties','Propriétés'],['slides','Liste des diapos'],['toolbar','Conseil de l’atelier']]" :key="key" class="menu-checkbox"><input type="checkbox" v-model="s.panels[key]">{{name}}</label><hr><button v-if="s.view==='slides'" @click="act(()=>{s.workspace='canvas';s.closeEdit();})">Voir le canvas du diaporama</button><button v-if="s.view==='slides'" @click="act(()=>s.workspace='editor')">Éditer la diapo</button><button @click="act(()=>s.panels.collapsed=!s.panels.collapsed)">Réduire / développer la navigation</button></template>
 <template v-else-if="menu==='Projet'"><label>{{s.documentScope==='banners'?'Nom de l’incrustation':'Nom du diaporama'}}<input type="text" v-model="s.project" maxlength="200" aria-label="Nom du projet"></label><small>{{s.documentScope==='banners'?'Incrustation · 16:9':s.slides.length+' diapo'+(s.slides.length>1?'s':'')+' · 16:9'}}</small><button @click="act(()=>{s.formatWidth=s.resolution.width;s.formatOpen=true;})">Format · {{s.resolution.width}} × {{s.resolution.height}} px</button><button @click="act(()=>s.view='themes')">Thème et palette du projet</button></template>
 <template v-else><button v-for="[type,label] in [['text','Texte'],['title','Titre'],['subtitle','Sous-titre'],['list','Liste'],['image','Image'],['code','Code Java'],['table','Tableau'],['bits','Octets et bits']]" :key="type" @click="add(type)"><Plus :size="14"/>{{label}}</button><button @click="act(()=>{s.workspace='editor';s.openShapes();})"><Plus :size="14"/>Formes</button><hr><button v-if="s.view==='slides'" @click="act(()=>s.add())">Nouvelle diapo</button></template>
 </div></div></nav></div>
 <div class="app-header-right"><span class="save-state" :title="s.saved?'Sauvegardé sur cet appareil':'Sauvegarde en cours'"><Check :size="14" v-if="s.saved"/><span>{{s.saved?(s.documentScope==='banners'?'Incrustation sauvegardée':'Diaporama sauvegardé'):'Sauvegarde…'}}</span></span><div class="workspace-switch" v-if="s.view==='slides'"><button :class="{active:s.workspace==='canvas'}" aria-label="Canvas" @click="s.workspace='canvas';s.closeEdit()"><LayoutGrid :size="15"/><span>Canvas</span></button><button :class="{active:s.workspace==='editor'}" aria-label="Éditer" @click="s.workspace='editor'"><Monitor :size="15"/><span>Éditer</span></button></div><button v-if="s.view==='banners'" class="btn primary" @click="s.openOverlayVideo()"><Play :size="16"/>Animer</button><button v-if="s.view==='banners'" class="btn" @click="s.overlayGallery=true"><LayoutGrid :size="16"/>Formats</button><button class="btn primary" v-if="s.view==='slides'" @click="s.startPresenter()" title="Lancer la présentation · F12" aria-keyshortcuts="F12"><Play :size="16"/><span>Présenter</span></button></div>
</header></template>
