<script setup>
import {computed} from 'vue';
import {bitValue,applyBitsPreset} from '../bits.js';
import PaletteColor from './PaletteColor.vue';
import InspectorDrawer from './InspectorDrawer.vue';
const props=defineProps({element:Object,position:Object,theme:Object,mode:String});const value=computed(()=>bitValue(props.element)),presetId=computed(()=>props.element.signed?({1:'byte',2:'short',4:'int',8:'long'}[props.element.bytes]||''):props.element.bytes===2?'char':'');
function dimensions(field,value){props.element[field]=Math.max(1,Math.min(8,Math.round(Number(value)||1)));adapt();}
function adapt(){if(!props.position)return;const rows=Math.ceil(props.element.bytes/Math.min(props.element.bytes,props.element.bytesPerRow)),height=Math.min(1000,72+rows*(126+(props.element.showWeights?22:0))+(rows-1)*20);props.position.h=height;props.position.y=Math.max(0,Math.min(props.position.y,1080-height-30));}
function preset(event){const id=event.target.value,bytes={byte:1,short:2,int:4,long:8,char:2};if(bytes[id]){props.element.bytes=bytes[id];props.element.signed=id!=='char';adapt();}}
</script>
<template><InspectorDrawer v-if="mode==='style'" id="bits-value" title="Octets et valeur"><label>Valeur décimale<input type="text" v-model="element.value" maxlength="80" aria-label="Valeur décimale des bits" spellcheck="false"></label><label>Largeur Java<select :value="presetId" aria-label="Préréglage entier Java" @change="preset"><option value="">Personnalisée</option><option v-for="id in ['byte','short','int','long','char']" :key="id" :value="id">{{id}}</option></select></label><div class="position-grid"><label>Octets<input type="number" min="1" max="8" :value="element.bytes" aria-label="Nombre d’octets" @input="dimensions('bytes',$event.target.value)"></label><label>Octets par ligne<input type="number" min="1" max="8" :value="element.bytesPerRow" aria-label="Octets par ligne" @input="dimensions('bytesPerRow',$event.target.value)"></label></div><label class="checkbox-label"><input type="checkbox" v-model="element.signed">Entier signé · complément à deux</label><p class="field-help" :class="{'bits-error':value.error}" role="status">{{value.error||'Plage : '+value.min+' à '+value.max}}</p><p class="field-help">8 bits par octet. Poids fort à gauche ; ordre pédagogique, sans représenter l’ordre des octets en mémoire. 3, 5, 6 et 7 octets sont des largeurs personnalisées.</p></InspectorDrawer><InspectorDrawer v-if="mode==='style'" id="bits-display" title="Affichage des bits"><label class="checkbox-label"><input type="checkbox" v-model="element.showValue">Valeur et taille</label><label class="checkbox-label"><input type="checkbox" v-model="element.showLabels">Numéro et valeur des octets</label><label class="checkbox-label"><input type="checkbox" v-model="element.showWeights">Poids des bits · 128 à 1</label><label>Arrondi<input type="number" min="0" max="24" v-model.number="element.radius" aria-label="Arrondi des bits"></label></InspectorDrawer><InspectorDrawer v-if="mode==='colors'" id="colors" title="Couleurs des bits"><div class="table-style-grid"><button class="btn" @click="applyBitsPreset(element,'theme')">Palette du thème</button><button class="btn" @click="applyBitsPreset(element,'reference')">Orange · référence</button></div><PaletteColor v-for="[field,label] in [['one','Bit à 1'],['zero','Bit à 0'],['border','Contours'],['oneText','Chiffre à 1'],['zeroText','Chiffre à 0']]" :key="field" :element="element" :field="field" :label="label" :theme="theme"/></InspectorDrawer></template>
