<script setup>
import { computed,ref } from 'vue';
import { Plus,Search,Trash2,Pencil,Check,Box } from 'lucide-vue-next';
import ComponentPreview from './ComponentPreview.vue';
const props=defineProps({studio:Object});const s=props.studio,query=ref(''),creating=ref(false),renaming=ref(null),name=ref('');
const filtered=computed(()=>s.components.filter(c=>c.name.toLocaleLowerCase().includes(query.value.toLocaleLowerCase())));
function create(){s.createComponent();creating.value=false;query.value='';}
function rename(c){if(name.value.trim())c.name=name.value.trim().slice(0,60);renaming.value=null;}
</script>
<template><section class="components-library"><div class="library-heading"><div><h3>Bibliothèque</h3><p>{{s.components.length}} composant{{s.components.length>1?'s':''}} dans ce projet</p></div><Box :size="22"/></div><button class="btn primary full" :disabled="!s.selectedKeys.length" @click="creating=!creating"><Plus :size="16"/>Créer avec la sélection</button><p class="field-help">{{s.selectedKeys.length?s.selectedKeys.length+' objet(s) à enregistrer':'Sélectionne des objets dans la diapo pour créer un composant.'}}</p><form v-if="creating" class="component-create" @submit.prevent="create"><label>Nom<input v-model="s.componentName" maxlength="60" aria-label="Nom du composant" required></label><div><button class="btn" type="button" @click="creating=false">Annuler</button><button class="btn primary" :disabled="!s.componentName.trim()||!s.selectedKeys.length">Créer</button></div></form><label class="library-search"><Search :size="16"/><input v-model="query" placeholder="Rechercher un composant…" aria-label="Rechercher un composant"></label><div v-if="!s.components.length" class="library-empty"><Box :size="32"/><strong>Ta bibliothèque commence ici</strong><p>Enregistre un titre, une carte ou un groupe d’objets pour le réutiliser dans tes diapos.</p></div><p v-else-if="!filtered.length" class="field-help">Aucun composant ne correspond à cette recherche.</p><article v-for="c in filtered" :key="c.id" class="component-card"><button class="component-insert-preview" :aria-label="'Insérer '+c.name" @click="s.useComponent(c)"><ComponentPreview :component="c" :theme="s.theme"/><span><Plus :size="16"/>Insérer</span></button><div class="component-card-info"><form v-if="renaming===c.id" @submit.prevent="rename(c)"><input v-model="name" aria-label="Nouveau nom du composant" maxlength="60" required><button class="icon-btn" aria-label="Valider le nom"><Check :size="16"/></button></form><template v-else><div><strong>{{c.name}}</strong><small>{{c.items.length}} objet{{c.items.length>1?'s':''}}</small></div><button class="icon-btn" :aria-label="'Renommer '+c.name" @click="renaming=c.id;name=c.name"><Pencil :size="14"/></button><button class="icon-btn" :aria-label="'Supprimer '+c.name" @click="s.deleteComponent(c.id)"><Trash2 :size="14"/></button></template></div></article><p v-if="s.components.length" class="field-help">Chaque insertion crée une copie personnalisable. Double-clique sur un membre pour modifier son texte.</p></section></template>
