<script setup>
import { computed } from 'vue';
import { themeColors } from '../themes.js';
import { fonts } from '../fonts.js';
const props=defineProps({studio:Object});const s=props.studio;
const type=computed(()=>s.multiType?.split(':')[0]);
const shapeFields=computed(()=>[
 ['filled','Remplissage','checkbox'],['fill','Couleur de remplissage','color'],['outlined','Contour','checkbox'],['stroke','Couleur du contour','color'],['strokeWidth','Épaisseur du contour','number',1,60],['opacity','Opacité (%)','number',0,100],['dashed','Pointillés','checkbox'],
 ...(s.multiType==='shape:rounded'?[['radius','Arrondi des coins (%)','number',0,45]]:[]),
 ...(s.multiType==='shape:star'?[['points','Branches','number',3,12],['innerRatio','Profondeur des branches','number',0.15,0.8]]:[]),
 ...(['shape:line','shape:curve'].includes(s.multiType)?[['roundedEnds','Extrémités arrondies','checkbox']]:[]),
]);
function value(scope,key){return s.commonProperty(scope,key);}
function number(scope,key,event,min,max,scale=1){if(event.target.value==='')return;let n=Number(event.target.value)/scale;if(['points','order'].includes(key))n=Math.round(n);if(Number.isFinite(n))s.updateCommon(scope,key,Math.max(min,Math.min(max,n)));}
</script>
<template><details v-if="s.multiType" class="property-details" open><summary>Modifier les {{s.selectedKeys.length}} objets ensemble</summary><p class="field-help">Valeurs différentes : champ vide ou « Mixte ». Seul le réglage modifié est appliqué à tous.</p>
 <div class="position-grid"><label v-for="[key,label,max] in [['w','Largeur',1920],['h','Hauteur',1080],['rotation','Rotation',180]]" :key="key">{{label}}<input type="number" :aria-label="label+' des objets'" :placeholder="value('position',key)===undefined?'Mixte':''" :value="value('position',key)===undefined?'':Math.round(value('position',key)*(key==='rotation'?1:s.resolution.width/1920)*100)/100" :step="1" @input="number('position',key,$event,key==='rotation'?-180:1,max,key==='rotation'?1:s.resolution.width/1920)"></label></div>
 <template v-if="type==='shape'"><label v-for="[key,label,kind,min,max] in shapeFields" :key="key" :class="{'checkbox-label':kind==='checkbox'}">{{label}}<span v-if="value('element',key)===undefined" class="field-help">Mixte</span><input v-if="kind==='checkbox'" type="checkbox" :aria-label="label+' des objets'" :checked="value('element',key)===true" :indeterminate="value('element',key)===undefined" @change="s.updateCommon('element',key,$event.target.checked)"><input v-else-if="kind==='color'" type="color" :aria-label="label+' des objets'" :value="value('element',key)||'#000000'" @input="s.updateCommon('element',key,$event.target.value)"><input v-else type="number" :aria-label="label+' des objets'" :min="min" :max="max" :step="key==='innerRatio'?0.01:1" :placeholder="'Mixte'" :value="value('element',key)??''" @input="number('element',key,$event,min,max)"></label><label v-if="s.multiType==='shape:line'">Orientation<select :value="value('element','direction')??''" @change="s.updateCommon('element','direction',$event.target.value)"><option disabled value="">Mixte</option><option value="horizontal">Horizontale</option><option value="vertical">Verticale</option><option value="down">Diagonale ↘</option><option value="up">Diagonale ↗</option></select></label></template>
 <template v-if="['text','code'].includes(type)"><label>Police d’écriture<select aria-label="Police des objets" :value="value('position','font')??''" @change="s.updateCommon('position','font',$event.target.value)"><option value="" disabled>Actuelle / mixte</option><option v-for="font in fonts.filter(f=>type!=='code'||f.mono)" :key="font.id" :value="font.id">{{font.name}}</option></select></label><label>Taille du texte<input type="number" aria-label="Taille du texte des objets" :value="value('position','size')===undefined?'':Math.round(value('position','size')*s.resolution.width/1920)" placeholder="Mixte" min="10" max="260" @input="number('position','size',$event,10,260,s.resolution.width/1920)"></label><label>Couleur du texte<select aria-label="Couleur du texte des objets" :value="value('style','colorRole')??''" @change="s.updateCommon('style','colorRole',$event.target.value||null);s.updateCommon('style','color',null)"><option value="">Automatique / mixte</option><option v-for="c in themeColors(s.theme)" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Couleur personnalisée<input type="color" aria-label="Couleur personnalisée des textes" :value="value('style','color')||s.theme.ink" @input="s.updateCommon('style','colorRole',null);s.updateCommon('style','color',$event.target.value)"></label><label v-for="[key,label] in [['italic','Italique'],['underline','Souligné'],['strike','Barré']]" :key="key" class="checkbox-label">{{label}}<input type="checkbox" :indeterminate="value('style',key)===undefined" :checked="value('style',key)===true" @change="s.updateCommon('style',key,$event.target.checked)"></label></template>
 <template v-if="type==='image'"><label>Cadrage<select :value="value('element','fit')??''" aria-label="Cadrage des images" @change="s.updateCommon('element','fit',$event.target.value)"><option value="" disabled>Mixte</option><option value="contain">Image entière</option><option value="cover">Remplir le cadre</option></select></label><label class="checkbox-label">Bords arrondis<input type="checkbox" :checked="value('element','roundedCorners')===true" :indeterminate="value('element','roundedCorners')===undefined" @change="s.updateCommon('element','roundedCorners',$event.target.checked)"></label><label>Arrondi (%)<input type="number" aria-label="Arrondi des images" min="0" max="50" :value="value('element','cornerRadius')??''" placeholder="Mixte" @input="number('element','cornerRadius',$event,0,50)"></label></template>
 <label>Étape d’apparition<input type="number" min="0" max="20" placeholder="Mixte" :value="value('fragment','order')??''" @input="number('fragment','order',$event,0,20)"></label><label>Animation<select :value="value('fragment','animation')??''" @change="s.updateCommon('fragment','animation',$event.target.value)"><option value="" disabled>Mixte</option><option value="fade">Fondu</option><option value="up">Montée douce</option><option value="zoom">Zoom léger</option><option value="none">Immédiate</option></select></label>
</details></template>
