<script setup>
import {reactive,ref,computed,watch,nextTick} from 'vue';
import {ChevronLeft,ChevronRight,Plus,Trash2,List} from 'lucide-vue-next';
import PedagogicalSteps from './PedagogicalSteps.vue';
const props=defineProps({studio:Object});const s=reactive(props.studio),open=ref(false);const count=computed(()=>s.baseSlide.pedagogicalSteps.length),root=ref(null),name=computed(()=>s.editStep?s.baseSlide.pedagogicalSteps[s.editStep-1]?.name:'État initial');
let previous;
watch(open,async value=>{if(value){previous=document.activeElement;await nextTick();root.value?.querySelector('button')?.focus();}else previous?.focus?.();});
function trap(event){if(event.key==='Escape'){open.value=false;return;}if(event.key!=='Tab')return;const list=[...root.value.querySelectorAll('button,input,select,textarea')].filter(el=>!el.disabled&&el.getClientRects().length),first=list[0],last=list.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
</script>
<template><section class="teaching-bar" aria-label="Étapes de la diapo"><span class="teaching-label">Étapes de la diapo</span><div class="teaching-selector"><button class="icon-btn" :disabled="!s.editStep" @click="s.selectPedagogicalStep(s.editStep-1)" aria-label="État précédent"><ChevronLeft :size="16"/></button><label class="teaching-select"><span class="step-count">{{s.editStep}} / {{count}}</span><select :value="s.editStep" @change="s.selectPedagogicalStep(Number($event.target.value))" aria-label="Choisir une étape de la diapo"><option :value="0">État initial</option><option v-for="(step,n) in s.baseSlide.pedagogicalSteps" :key="step.id" :value="n+1">{{n+1}} · {{step.name}}</option></select></label><button class="icon-btn" :disabled="s.editStep===count" @click="s.selectPedagogicalStep(s.editStep+1)" aria-label="État suivant"><ChevronRight :size="16"/></button></div><button class="icon-btn" :disabled="!s.editStep" @click="s.removePedagogical(s.editStep)" :aria-label="'Supprimer '+name" title="Supprimer l’étape sélectionnée · Ctrl Z pour annuler"><Trash2 :size="15"/></button><button class="btn teaching-add" :disabled="count>=20" @click="s.addPedagogical" title="Dupliquer cet état"><Plus :size="15"/><span>Étape</span></button><button class="btn teaching-manage" @click="open=true" aria-label="Gérer les étapes de la diapo"><List :size="15"/><span>Gérer</span></button><Teleport to="body"><div v-if="open" class="modal-backdrop" @pointerdown.stop @keydown.stop="trap" @click.self="open=false"><section ref="root" class="teaching-manager" role="dialog" aria-modal="true" aria-label="Gérer les étapes de la diapo"><div class="text-dialog-heading"><div><h2>Les étapes de cette diapo</h2><p>Un parcours clair, sans multiplier les diapos.</p></div><button class="btn" @click="open=false">Fermer</button></div><PedagogicalSteps :studio="s"/><button class="btn primary full" @click="open=false">Revenir à l’éditeur</button></section></div></Teleport></section></template>
