<script setup>
import { reactive,ref,watch,nextTick,provide,computed } from 'vue';
import { fonts,fontCss } from '../fonts.js';
import { textRoles,textRole } from '../textRoles.js';
import { presets,visibleBlocks,blockLabel,blockType } from '../model.js';
import { slideAnchors } from '../slidePlacement.js';
import { Pencil,Copy,Trash2,Play,SlidersHorizontal,Palette,Move, Sparkles,Layers,Box,Square,Presentation } from 'lucide-vue-next';
import PedagogicalSteps from './PedagogicalSteps.vue';
import NotesEditor from './NotesEditor.vue';
import MotionProperties from './MotionProperties.vue';
import NumberRange from './NumberRange.vue';
import InspectorDrawer from './InspectorDrawer.vue';
import TableProperties from './TableProperties.vue';
import ShapeProperties from './ShapeProperties.vue';
import TextStyleProperties from './TextStyleProperties.vue';
import ListProperties from './ListProperties.vue';
import AppearanceOrder from './AppearanceOrder.vue';
import ComponentsPanel from './ComponentsPanel.vue';
import MultiProperties from './MultiProperties.vue';
const props=defineProps({studio:Object}),s=reactive(props.studio),section=ref('element'),category=ref('style'),body=ref(null),scrolls={};
provide('inspectorDrawers',reactive({}));
const tabs=computed(()=>[['element','Objet',Square],['slide',s.view==='banners'?'Format':'Diapo',Presentation],['layers','Calques',Layers],['components','Composants',Box]]),categories=[['style','Style',SlidersHorizontal],['colors','Couleurs',Palette],['layout','Placement',Move],['motion','Animation',Sparkles]];
const scrollKey=computed(()=>section.value+':'+(section.value==='element'?category.value:''));
function switchTo(target){if(body.value)scrolls[scrollKey.value]=body.value.scrollTop;section.value=target;nextTick(()=>{if(body.value)body.value.scrollTop=scrolls[scrollKey.value]||0;});}
function chooseCategory(target){if(body.value)scrolls[scrollKey.value]=body.value.scrollTop;category.value=target;nextTick(()=>{if(body.value)body.value.scrollTop=scrolls[scrollKey.value]||0;});}
watch(()=>s.selectionScope,value=>{if(!['layers','components'].includes(section.value))switchTo(value==='slides'?'slide':'element');});
watch(()=>s.selectedKeys.join('|'),()=>{if(s.selectedKeys.length&&section.value==='slide'&&s.selectionScope==='elements')switchTo('element');const top=body.value?.scrollTop||0;nextTick(()=>{if(body.value)body.value.scrollTop=top;});},{flush:'pre'});
const pixels=v=>Math.round(v*s.resolution.width/1920),isText=computed(()=>['text','code'].includes(s.selectedType)),object=computed(()=>s.current.elements[s.selected]);
</script>
<template><aside class="inspector properties-panel slim-inspector"><button class="panel-resizer" @pointerdown="s.resizePanel($event,'inspectorWidth')" aria-label="Redimensionner les propriétés"></button>
 <div class="properties-heading"><strong>Propriétés</strong><small>{{s.selectedKeys.length?s.selectedKeys.length+' objet'+(s.selectedKeys.length>1?'s':''):''}}</small></div>
 <div class="inspector-navigation" aria-label="Rubriques des propriétés"><button v-for="[id,label,icon] in tabs" :key="id" :class="{active:section===id}" :aria-label="label+' · propriétés'" :aria-pressed="section===id" @click="switchTo(id)"><component :is="icon" :size="16"/><span>{{label}}</span></button></div>
 <div v-if="section==='element'&&s.selectedKeys.length" class="inspector-object"><div><strong>{{s.selected?blockLabel(s.current,s.selected):'Sélection multiple'}}</strong><small>{{({text:'Texte',code:'Code Java',shape:'Forme',image:'Image',table:'Tableau'})[s.selectedKeys.length>1?s.multiType?.split(':')[0]:s.selectedType]||'Groupe d’objets'}}</small></div><button v-if="s.selected&&(isText||s.selectedType==='table')" class="icon-btn" aria-label="Éditer le contenu" title="Éditer le contenu" @click="s.workspace='editor';s.editSelected()"><Pencil :size="15"/></button><button class="icon-btn" @click="s.duplicateSelected" aria-label="Dupliquer la sélection" title="Dupliquer · Ctrl D"><Copy :size="15"/></button><button class="icon-btn" @click="s.removeBlock" aria-label="Supprimer la sélection" title="Supprimer"><Trash2 :size="15"/></button></div>
 <div v-if="section==='element'&&s.selectedKeys.length" class="inspector-categories"><button v-for="[id,label,icon] in categories" :key="id" :class="{active:category===id}" :aria-pressed="category===id" @click="chooseCategory(id)"><component :is="icon" :size="14"/><span>{{label}}</span></button></div>
 <div ref="body" class="inspector-body">
 <ComponentsPanel v-if="section==='components'" :studio="s"/>
 <section v-else-if="section==='layers'" class="layers-panel"><p class="field-help">Premier plan en haut · {{visibleBlocks(s.current).length}} objets</p><InspectorDrawer v-if="s.selectedKeys.length" id="layers-order" title="Superposition"><div class="layer-controls"><button v-for="[id,name] in [['front','Premier plan'],['back','Arrière-plan'],['forward','Avancer'],['backward','Reculer']]" :key="id" class="btn" @click="s.setLayer(id)">{{name}}</button></div><label>Rang · z-index<input type="number" min="1" :max="visibleBlocks(s.current).length" :value="Math.min(...s.selectedKeys.map(k=>visibleBlocks(s.current).indexOf(k)+1))" aria-label="Rang de la sélection" @input="s.setLayer('rank',$event.target.value)"></label></InspectorDrawer><button v-for="(key,n) in visibleBlocks(s.current).slice().reverse()" :key="key" :class="['layer-row',{active:s.selectedKeys.includes(key)}]" :aria-pressed="s.selectedKeys.includes(key)" @click="s.selectLayer(key,$event)"><span class="layer-rank">{{visibleBlocks(s.current).length-n}}</span><span><strong>{{blockLabel(s.current,key)}}</strong><small>{{({text:'Texte',code:'Code Java',shape:'Forme',image:'Image',table:'Tableau'})[blockType(s.current,key)]}}</small></span></button><p class="field-help">Ctrl + clic pour sélectionner plusieurs calques.</p></section>
 <template v-else-if="section==='element'">
 <InspectorDrawer v-if="s.selectedKeys.length&&category==='colors'" id="object-opacity" title="Opacité"><NumberRange label="Opacité des éléments" unit="%" :model-value="s.selectedOpacity" @update:model-value="s.updateOpacity"/><p v-if="s.selectedKeys.length>1" class="field-help">Le curseur applique la même opacité à tous les objets sélectionnés.</p></InspectorDrawer>
 <p v-if="!s.selectedKeys.length" class="inspector-empty">Sélectionne un objet pour le personnaliser.</p>
 <InspectorDrawer v-if="s.selectedKeys.length>1&&!s.multiType&&category==='layout'" id="selection-frame" title="Cadre de la sélection"><div class="position-grid"><label v-for="[key,name] in [['x','Gauche'],['y','Haut'],['w','Largeur'],['h','Hauteur']]" :key="key">{{name}}<output>{{pixels(s.selectionBounds?.[key]||0)}} px</output></label></div></InspectorDrawer><InspectorDrawer v-if="s.selectedKeys.length>1&&!s.multiType&&category==='motion'" id="multi-motion" title="Apparition du groupe"><label>Étape<input type="number" min="0" max="20" :value="s.commonProperty('fragment','order')??''" placeholder="Mixte" @change="s.updateAppearance(s.selectedKeys,'order',$event.target.value)"></label><MotionProperties :animation="s.commonProperty('fragment','animation')" :exit-animation="s.commonProperty('fragment','exitAnimation')" @change="(field,value)=>s.updateAppearance(s.selectedKeys,field,value)"/></InspectorDrawer><MultiProperties v-if="s.selectedKeys.length>1" :studio="s" :mode="category"/>
 <template v-if="s.selected&&s.selectedKeys.length===1">
 <div v-show="category==='style'">
  <InspectorDrawer id="identity" title="Nom de l’objet"><label>Nom<input v-model="s.selectedName" :placeholder="blockLabel(s.current,s.selected)" maxlength="100" aria-label="Nom de l’élément"></label></InspectorDrawer>
  <InspectorDrawer v-if="isText" id="typography" title="Typographie"><label v-if="s.selectedType==='text'">Style de texte<select :value="textRole(s.current,s.selected).id" aria-label="Style de texte" @change="s.setTextRole($event.target.value)"><option v-for="role in textRoles" :key="role.id" :value="role.id">{{role.name}} · {{role.font==='inter'?'Inter':'Montserrat'}}</option></select></label><label>Taille · px<input type="number" aria-label="Taille du texte" :value="pixels(s.position.size)" min="10" :max="pixels(260)" @change="s.setPosition('size',$event)"></label><label>Police<select v-model="s.position.font" aria-label="Police de l’élément" @change="s.refreshTextStyle();s.fitSelection()"><option v-if="!s.position.font" :value="undefined">{{s.selectedType==='code'?'Monospace système':textRole(s.current,s.selected).font==='inter'?'Inter':'Montserrat'}}</option><optgroup v-for="local in [false,true]" :key="String(local)" :label="local?'Polices système':'Polices incluses'"><option v-for="f in fonts.filter(f=>!!f.local===local&&(s.selectedType!=='code'||f.mono))" :key="f.id" :value="f.id">{{f.name}}</option></optgroup></select></label><p v-if="s.fontLoading" class="field-help">Chargement de la police…</p><TextStyleProperties :value="s.selectedTextStyle" :font="s.position.font" :type="s.selectedType" :theme="s.theme" @change="s.updateTextStyle"/></InspectorDrawer>
  <InspectorDrawer v-if="s.selectedType==='text'" id="lists" title="Listes"><ListProperties :value="s.selectedTextStyle.list" :theme="s.theme" :scale="s.resolution.width/1920" @change="s.updateTextStyle"/></InspectorDrawer>
  <InspectorDrawer v-if="s.selectedType==='text'" id="text-frame" title="Cadre du texte"><label class="checkbox-label"><input type="checkbox" v-model="s.position.autoSize" @change="s.position.wrapWidth||=s.position.w;s.fitSelection()">Ajuster au contenu</label><label v-if="s.position.autoSize">Largeur maximale · px<input type="number" aria-label="Largeur maximale du texte" :value="pixels(s.position.wrapWidth)" min="80" :max="s.resolution.width" @change="s.position.wrapWidth=Math.max(80,Math.min(1920,Number($event.target.value)*1920/s.resolution.width));s.fitSelection()"></label></InspectorDrawer>
  <InspectorDrawer v-if="s.selectedType==='code'" id="code-caption" title="Titre du code"><label>Nom de fichier<input v-model="s.codeCaption" maxlength="200" placeholder="HelloWorld.java" aria-label="Titre de l’extrait de code"></label></InspectorDrawer>
  <InspectorDrawer v-if="s.selectedType==='shape'" id="shape-style" title="Forme et contour"><ShapeProperties :theme="s.theme" :shape="object" :scale="s.resolution.width/1920"/></InspectorDrawer>
  <InspectorDrawer v-if="s.selectedType==='image'" id="image-style" title="Image et cadrage"><label class="image-upload">{{object.src?'Remplacer l’image':'Importer une image'}}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" @change="s.uploadImage"></label><label>Cadrage<select v-model="object.fit"><option value="contain">Image entière</option><option value="cover">Remplir le cadre</option></select></label><label class="checkbox-label"><input type="checkbox" v-model="object.roundedCorners">Bords arrondis</label><NumberRange v-if="object.roundedCorners" label="Arrondi de l’image" unit="%" :max="50" :model-value="object.cornerRadius??10" @update:model-value="object.cornerRadius=$event"/><label class="checkbox-label"><input type="checkbox" v-model="object.background">Fond du thème derrière l’image</label><p class="field-help">PNG, WebP et SVG : transparence conservée.</p></InspectorDrawer>
 </div>
 <div v-show="category==='colors'">
  <InspectorDrawer v-if="isText||s.selectedType==='shape'" id="colors" title="Couleurs"><TextStyleProperties v-if="isText" mode="colors" :value="s.selectedTextStyle" :font="s.position.font" :type="s.selectedType" :theme="s.theme" @change="s.updateTextStyle"/><ShapeProperties v-else mode="colors" :theme="s.theme" :shape="object" :scale="s.resolution.width/1920"/></InspectorDrawer>
  <InspectorDrawer v-if="s.selectedType==='image'" id="colors" title="Fond de l’image"><label class="checkbox-label"><input type="checkbox" v-model="object.background">Fond du thème derrière l’image</label><p class="field-help">Les couleurs de la photo sont conservées. Le fond suit la palette du diaporama.</p></InspectorDrawer>
 </div>
 <TableProperties v-if="s.selectedType==='table'&&['style','colors','layout'].includes(category)" :mode="category" :table="object" :position="s.position" @edit="s.workspace='editor';s.editSelected()" :theme="s.theme" :scale="s.resolution.width/1920"/>
 <InspectorDrawer v-show="category==='layout'" id="geometry" title="Position et dimensions"><div class="position-grid"><label v-for="[key,name] in [['x','Gauche'],['y','Haut'],['w','Largeur'],['h','Hauteur']]" :key="key">{{name}}<input type="number" :aria-label="name+' de l’élément'" :value="pixels(s.selectedType==='shape'?s.selectedBounds?.[key]||0:s.position[key]??(key==='h'?s.selectedBounds?.h||0:0))" min="0" :max="key==='y'||key==='h'?s.resolution.height:s.resolution.width" @change="s.setPosition(key,$event)"></label></div><label>Rotation · degrés<input type="number" aria-label="Rotation de l’élément" :value="Math.round((s.position.rotation||0)*100)/100" @change="s.setRotation"></label></InspectorDrawer>
 <InspectorDrawer v-show="category==='motion'" id="appearance" title="Apparition"><label>Étape<input type="number" min="0" max="20" :value="s.current.fragments[s.selected].order" @input="s.updateFragment"></label><MotionProperties :animation="s.current.fragments[s.selected].animation" :exit-animation="s.current.fragments[s.selected].exitAnimation" @change="(field,value)=>s.updateAppearance([s.selected],field,value)"/><p class="field-help">Étape 0 : visible au départ. Espace révèle chaque étape suivante.</p></InspectorDrawer>
 </template>
 <template v-if="s.selectedKeys.length&&category==='layout'">
  <InspectorDrawer v-if="s.selectedKeys.length>1" id="group-layout" title="Alignement et espacement"><div class="group-layout"><button class="btn full" @click="s.centerObjects('x')">Centrer horizontalement</button><button class="btn full" @click="s.centerObjects('y')">Centrer verticalement</button><button class="btn full" @click="s.arrangeObjects('x','line')">Disposer en ligne</button><button class="btn full" @click="s.arrangeObjects('y','line')">Disposer en colonne</button><label>Espacement · px<input type="number" min="0" v-model.number="s.spacing" aria-label="Espacement des éléments"></label><button class="btn full" @click="s.arrangeObjects('x','spacing')">Espacer horizontalement</button><button class="btn full" @click="s.arrangeObjects('y','spacing')">Espacer verticalement</button><button class="btn full" @click="s.groupObjects">Grouper · Ctrl G</button><button v-if="s.canUngroup" class="btn full" @click="s.ungroupObjects">Dissocier · Ctrl Maj G</button><button class="btn full" @click="s.copySelection">Copier · Ctrl C</button></div></InspectorDrawer>
  <InspectorDrawer id="selection-scale" title="Mise à l’échelle"><label class="checkbox-label"><input type="checkbox" :checked="s.scaleMode||s.selectedKeys.length>1" :disabled="s.selectedKeys.length>1" @change="s.scaleMode=$event.target.checked">Poignées proportionnelles</label><p class="field-help">Les coins adaptent ensemble les objets, textes, contours et espacements.</p><label>Échelle à appliquer · %<input type="number" min="1" max="1000" v-model.number="s.scalePercent" aria-label="Échelle de la sélection"></label><button class="btn full" @click="s.applySelectionScale">Appliquer l’échelle</button></InspectorDrawer><InspectorDrawer id="slide-placement" title="Placer sur la diapo"><div class="slide-anchor-grid"><button v-for="[x,y,label,icon] in slideAnchors" :key="x+y" class="btn" :aria-label="label" @click="s.placeObjects(x,y)"><span aria-hidden="true">{{icon}}</span><small>{{label}}</small></button></div><label>Marge · px<input type="number" min="0" :max="s.resolution.height/2" v-model.number="s.placementMargin" aria-label="Marge de positionnement"></label></InspectorDrawer>
  <InspectorDrawer id="object-order" title="Superposition"><div class="layer-controls"><button v-for="[id,name] in [['front','Premier plan'],['back','Arrière-plan'],['forward','Avancer'],['backward','Reculer']]" :key="id" class="btn" @click="s.setLayer(id)">{{name}}</button></div><label>Rang · z-index<input type="number" min="1" :max="visibleBlocks(s.current).length" :value="Math.min(...s.selectedKeys.map(k=>visibleBlocks(s.current).indexOf(k)+1))" aria-label="Rang de la sélection" @input="s.setLayer('rank',$event.target.value)"></label></InspectorDrawer>
 </template>
 </template>
 <template v-else-if="section==='slide'&&s.view==='banners'"><InspectorDrawer id="overlay-format" title="Composition"><label>Nom de l’incrustation<input v-model="s.current.overlayName" maxlength="100"></label><button class="btn full" @click="s.overlayGallery=true">Choisir un format · 24 aperçus</button><p class="field-help">Tous les calques sont éditables. Le PNG conserve la transparence.</p></InspectorDrawer><InspectorDrawer id="overlay-appearances" title="Ordre des apparitions"><AppearanceOrder :slide="s.current" @change="s.updateAppearance"/></InspectorDrawer></template><template v-else-if="section==='slide'"><button class="btn full" @click="s.startPresentation(false)"><Play :size="14"/>Tester cette diapo</button><InspectorDrawer id="pedagogical-steps" title="Étapes pédagogiques"><PedagogicalSteps :studio="s"/></InspectorDrawer><InspectorDrawer id="slide-composition" title="Composition"><label>Disposition<select v-model="s.current.layout" @change="s.applyPreset(s.current.layout)"><option v-for="p in presets" :key="p.id" :value="p.id">{{p.name}}</option></select></label><button class="btn full" @click="s.applyPreset(s.current.layout)">Réappliquer la disposition</button><button v-if="s.canUndoLayout" class="btn full" @click="s.undoLayout">Annuler la recomposition</button></InspectorDrawer><InspectorDrawer id="slide-transition" title="Transition"><p class="field-help">{{s.exitLabel}}</p><label>Sortie vers<select v-model="s.current.exitDirection" aria-label="Direction de sortie"><option value="auto">Automatique · canvas</option><option value="left">← Gauche</option><option value="right">→ Droite</option><option value="up">↑ Haut</option><option value="down">↓ Bas</option></select></label><label>Durée<select v-model.number="s.transitionMs"><option :value="0">Immédiate</option><option :value="350">350 ms</option><option :value="650">650 ms</option><option :value="1000">1 seconde</option></select></label></InspectorDrawer><InspectorDrawer id="slide-appearances" title="Ordre des apparitions"><AppearanceOrder :slide="s.current" @change="s.updateAppearance"/></InspectorDrawer><InspectorDrawer id="slide-notes" title="Notes de présentation"><NotesEditor v-model="s.current.notes" :label="s.editStep?'Notes de cette étape':'Notes de l’état initial'"/></InspectorDrawer></template>
 </div></aside></template>
