<script setup>
import {computed,ref,onUnmounted} from 'vue';
import {tableTracks,resizeTableDivider} from '../tables.js';
const props=defineProps({table:Object,position:Object});const emit=defineEmits(['preview','commit']);const draft=ref(null),root=ref(null);let gesture=null;
const tracks=computed(()=>tableTracks(draft.value||props.table,props.position));const frame=computed(()=>({left:props.position.x/1920*100+'%',top:props.position.y/1080*100+'%',width:props.position.w/1920*100+'%',height:(props.position.h||400)/1080*100+'%',transform:`rotate(${props.position.rotation||0}deg)`}));
function start(event,axis,index){if(event.button!==0)return;event.preventDefault();const stage=root.value.parentElement.getBoundingClientRect();gesture={axis,index,x:event.clientX,y:event.clientY,scale:1920/stage.width,table:{...props.table,columnWeights:props.table.columnWeights.slice(),rowWeights:props.table.rowWeights.slice()}};event.currentTarget.setPointerCapture(event.pointerId);}
function move(event){if(!gesture)return;const angle=-(props.position.rotation||0)*Math.PI/180,dx=(event.clientX-gesture.x)*gesture.scale,dy=(event.clientY-gesture.y)*gesture.scale,delta=gesture.axis==='columns'?dx*Math.cos(angle)-dy*Math.sin(angle):dx*Math.sin(angle)+dy*Math.cos(angle),weights=resizeTableDivider(gesture.table,props.position,gesture.axis,gesture.index,delta);draft.value={...gesture.table,...weights};emit('preview',draft.value);}
function end(event){if(!gesture)return;if(event.type!=='pointerup')emit('preview',null);else if(draft.value)emit('commit',{columnWeights:draft.value.columnWeights,rowWeights:draft.value.rowWeights});gesture=null;draft.value=null;emit('preview',null);}
function key(event,axis,index){const delta=event.key==='ArrowLeft'||event.key==='ArrowUp'?-1:event.key==='ArrowRight'||event.key==='ArrowDown'?1:0;if(!delta)return;event.preventDefault();event.stopPropagation();emit('commit',resizeTableDivider(props.table,props.position,axis,index,delta*(event.shiftKey?10:1)));}
onUnmounted(()=>emit('preview',null));
</script>
<template><div ref="root" class="table-dividers" :style="frame"><button v-for="(col,c) in tracks.columns.slice(0,-1)" :key="'c'+c" class="table-divider column-divider" :style="{left:(col.at+col.size)/position.w*100+'%'}" :aria-label="'Ajuster la séparation des colonnes '+(c+1)+' et '+(c+2)" title="Déplacer pour ajuster les colonnes · flèches au clavier" @pointerdown.stop="start($event,'columns',c)" @pointermove.stop="move" @pointerup.stop="end" @pointercancel.stop="end" @lostpointercapture.stop="end" @keydown="key($event,'columns',c)"><span></span></button><button v-for="(row,r) in tracks.rows.slice(0,-1)" :key="'r'+r" class="table-divider row-divider" :style="{top:(row.at+row.size)/(position.h||400)*100+'%'}" :aria-label="'Ajuster la séparation des lignes '+(r+1)+' et '+(r+2)" title="Déplacer pour ajuster les lignes · flèches au clavier" @pointerdown.stop="start($event,'rows',r)" @pointermove.stop="move" @pointerup.stop="end" @pointercancel.stop="end" @lostpointercapture.stop="end" @keydown="key($event,'rows',r)"><span></span></button></div></template>
