<script setup>
import { ref, watch } from 'vue';
import { resizeTable } from '../tables.js';
import { fonts } from '../fonts.js';
import PaletteColor from './PaletteColor.vue';
const props=defineProps({table:Object,theme:Object,scale:Number});const editing=ref(false),draft=ref([]);
function open(){draft.value=props.table.cells.map(row=>row.slice());editing.value=true;}
function commit(){props.table.cells=draft.value.map(row=>row.slice());editing.value=false;}
watch(()=>props.table,()=>{editing.value=false;});
function resize(field,value){resizeTable(props.table,field==='rows'?value:props.table.rows,field==='columns'?value:props.table.columns);}
</script>
<template><details class="property-details" open><summary>Tableau</summary><div class="position-grid"><label>Lignes<input type="number" min="1" max="20" aria-label="Nombre de lignes" :value="table.rows" @input="resize('rows',$event.target.value)"></label><label>Colonnes<input type="number" min="1" max="10" aria-label="Nombre de colonnes" :value="table.columns" @input="resize('columns',$event.target.value)"></label></div><button class="btn full" @click="open">Modifier les cellules</button><p class="field-help">Jusqu’à 20 lignes et 10 colonnes. Réduire le tableau retire les cellules en dehors du nouveau cadre ; Ctrl Z annule.</p><label class="checkbox-label"><input type="checkbox" v-model="table.header">Première ligne d’en-tête</label><label class="checkbox-label"><input type="checkbox" v-model="table.striped">Lignes alternées</label><label>Police<select v-model="table.font" aria-label="Police du tableau"><option v-for="f in fonts" :key="f.id" :value="f.id">{{f.name}}</option></select></label><label>Taille du texte · px<input type="number" min="10" :max="120*scale" :value="Math.round(table.fontSize*scale)" aria-label="Taille du texte du tableau" @change="table.fontSize=Math.max(10,Math.min(120,Number($event.target.value)/scale||30))"></label><label>Alignement des cellules<select v-model="table.align"><option value="left">Gauche</option><option value="center">Centre</option><option value="right">Droite</option></select></label><label>Marge des cellules · px<input type="number" min="0" :max="80*scale" :value="Math.round(table.padding*scale)" @change="table.padding=Math.max(0,Math.min(80,Number($event.target.value)/scale||0))"></label><label>Épaisseur des bordures · px<input type="number" min="0" :max="12*scale" :value="table.borderWidth*scale" @change="table.borderWidth=Math.max(0,Math.min(12,Number($event.target.value)/scale||0))"></label><details class="property-details"><summary>Couleurs du tableau</summary><PaletteColor v-for="[field,label] in [['fill','Fond des cellules'],['headerFill','Fond de l’en-tête'],['textColor','Texte des cellules'],['headerText','Texte de l’en-tête'],['border','Bordures']]" :key="field" :element="table" :field="field" :label="label" :theme="theme"/></details></details>
<Teleport to="body"><div v-if="editing" class="gallery-backdrop" @keydown.esc.stop="editing=false" @click.self="editing=false"><section class="table-dialog" role="dialog" aria-modal="true" aria-label="Modifier les cellules du tableau"><div class="gallery-heading"><div><h2>Contenu du tableau</h2><p>{{table.rows}} lignes × {{table.columns}} colonnes</p></div><button class="btn" @click="editing=false">Annuler</button></div><div class="table-cell-scroll"><table><tbody><tr v-for="(row,r) in draft" :key="r"><td v-for="(_,c) in row" :key="c"><label>L{{r+1}} · C{{c+1}}<textarea :aria-label="'Cellule ligne '+(r+1)+' colonne '+(c+1)" v-model="draft[r][c]" maxlength="2000" rows="3"></textarea></label></td></tr></tbody></table></div><div class="dialog-actions"><button class="btn primary" @click="commit">Valider les cellules</button></div></section></div></Teleport></template>
