<script setup>
import {ref,computed,onMounted,onUnmounted,nextTick} from 'vue';
import {isHeaderCell,cellTextStyle} from '../tables.js';
import {fonts,fontCss} from '../fonts.js';
import {themeColors} from '../themes.js';
import {boundColor} from '../colors.js';
import {X,Check} from 'lucide-vue-next';
const props=defineProps({table:Object,theme:Object,scale:{type:Number,default:1}});const emit=defineEmits(['confirm','close']);const draft=ref(props.table.cells.map(row=>row.slice())),styles=ref(JSON.parse(JSON.stringify(props.table.cellStyles||{}))),selection=ref([]),dialog=ref(null);let previous,anchor=null;
const selectionSet=computed(()=>new Set(selection.value));
function confirm(){emit('confirm',draft.value.map(row=>row.slice()),styles.value);}
function toggle(r,c,event){const key=r+':'+c;if(event.shiftKey&&anchor){const [ar,ac]=anchor;selection.value=[];for(let y=Math.min(ar,r);y<=Math.max(ar,r);y++)for(let x=Math.min(ac,c);x<=Math.max(ac,c);x++)selection.value.push(y+':'+x);}else{selection.value=selectionSet.value.has(key)?selection.value.filter(k=>k!==key):[...selection.value,key];anchor=[r,c];}}
function selectAxis(axis,index){selection.value=[];for(let r=0;r<props.table.rows;r++)for(let c=0;c<props.table.columns;c++)if(axis==='all'||axis==='row'&&r===index||axis==='column'&&c===index)selection.value.push(r+':'+c);}
function effective(key){const [r,c]=key.split(':').map(Number);return cellTextStyle({...props.table,cellStyles:styles.value},r,c);}
function common(field){const values=selection.value.map(key=>effective(key)[field]);return values.length&&values.every(value=>value===values[0])?values[0]:'';}
function apply(field,value){for(const key of selection.value)styles.value[key]={...styles.value[key],[field]:value};}
function size(value){if(value==='')return;const n=Number(value)/props.scale;if(Number.isFinite(n)&&n>=10&&n<=120)apply('fontSize',n);}
function reset(){for(const key of selection.value)delete styles.value[key];}
function custom(field,value){if(!/^#[\da-f]{6}$/i.test(value))return;apply(field,value);apply(field+'Role',null);}
function color(field){const key=selection.value[0];return key?boundColor(effective(key),field,props.theme):'#ffffff';}
function preview(r,c){const cell=effective(r+':'+c);return {color:boundColor(cell,'textColor',props.theme),background:boundColor(cell,'fill',props.theme),fontFamily:fontCss(cell.font),fontWeight:cell.bold?700:400,textAlign:cell.align};}
function key(e){if(e.key==='Escape'){e.preventDefault();emit('close');}else if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();confirm();}else if(e.key==='Tab'){const list=[...dialog.value.querySelectorAll('button,textarea,input,select')].filter(el=>!el.disabled&&el.getClientRects().length),first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
onMounted(()=>{previous=document.activeElement;nextTick(()=>dialog.value?.querySelector('textarea')?.focus());});onUnmounted(()=>previous?.focus?.());
</script>
<template><div class="modal-backdrop" @keydown.stop="key" @pointerdown.stop><form ref="dialog" class="table-dialog" role="dialog" aria-modal="true" aria-labelledby="table-dialog-title" @submit.prevent="confirm"><div class="text-dialog-heading"><div><h2 id="table-dialog-title">Modifier les cellules</h2><p>{{table.rows}} lignes × {{table.columns}} colonnes · texte et styles</p></div><button type="button" class="icon-btn" aria-label="Fermer sans appliquer" @click="emit('close')"><X :size="20"/></button></div>
<div class="table-cell-selection"><button type="button" class="btn" @click="selectAxis('all')">Tout sélectionner</button><button type="button" class="btn" :disabled="!selection.length" @click="selection=[]">Désélectionner</button><span>{{selection.length}} cellule{{selection.length>1?'s':''}} sélectionnée{{selection.length>1?'s':''}}</span></div>
<div v-if="selection.length" class="table-cell-style"><div class="position-grid"><label>Police des cellules<select :value="common('font')" aria-label="Police des cellules sélectionnées" @change="apply('font',$event.target.value)"><option value="" disabled>Mixte</option><option v-for="font in fonts" :key="font.id" :value="font.id">{{font.name}}</option></select></label><label>Taille · px<input type="number" step="any" :min="10*scale" :max="120*scale" :value="common('fontSize')===''?'':Math.round(common('fontSize')*scale)" placeholder="Mixte" aria-label="Taille des cellules sélectionnées" @input="size($event.target.value)" @change="size($event.target.value)"></label><label>Graisse<select :value="String(common('bold'))" aria-label="Graisse des cellules sélectionnées" @change="apply('bold',$event.target.value==='true')"><option value="" disabled>Mixte</option><option value="false">Normal</option><option value="true">Gras</option></select></label><label>Alignement<select :value="common('align')" aria-label="Alignement des cellules sélectionnées" @change="apply('align',$event.target.value)"><option value="" disabled>Mixte</option><option value="left">Gauche</option><option value="center">Centre</option><option value="right">Droite</option></select></label><label>Vertical<select :value="common('verticalAlign')" aria-label="Alignement vertical des cellules sélectionnées" @change="apply('verticalAlign',$event.target.value)"><option value="" disabled>Mixte</option><option value="top">Haut</option><option value="middle">Centre</option><option value="bottom">Bas</option></select></label><label v-for="[field,label] in [['fill','Fond'],['textColor','Texte']]" :key="field">{{label}}<span class="cell-color-control"><select :value="common(field+'Role')||''" :aria-label="label+' des cellules · palette'" @change="apply(field+'Role',$event.target.value||null)"><option value="">Personnalisée / mixte</option><option v-for="color in themeColors(theme)" :key="color.id" :value="color.id">{{color.name}}</option></select><input type="color" :value="color(field)" :aria-label="label+' des cellules · couleur'" @input="custom(field,$event.target.value)"></span></label></div><button type="button" class="btn" @click="reset">Reprendre le style du tableau</button></div>
<p class="field-help">Coche les cellules à personnaliser. Maj + clic sélectionne un rectangle ; les boutons de ligne et colonne sélectionnent une rangée entière.</p>
<div class="table-cell-scroll"><table><thead><tr><th></th><th v-for="c in table.columns" :key="c"><button type="button" class="btn" @click="selectAxis('column',c-1)" :aria-label="'Sélectionner la colonne '+c">Colonne {{c}}</button></th></tr></thead><tbody><tr v-for="(row,r) in draft" :key="r"><th><button type="button" class="btn" @click="selectAxis('row',r)" :aria-label="'Sélectionner la ligne '+(r+1)">{{r+1}}</button></th><td v-for="(_,c) in row" :key="c" :class="{headerCell:isHeaderCell(table,r,c),cellSelected:selectionSet.has(r+':'+c)}"><div class="cell-caption"><label><input type="checkbox" :checked="selectionSet.has(r+':'+c)" :aria-label="'Sélectionner cellule ligne '+(r+1)+' colonne '+(c+1)" @click="toggle(r,c,$event)">L{{r+1}} · C{{c+1}}</label><small v-if="styles[r+':'+c]">Style personnalisé</small></div><textarea :style="preview(r,c)" :aria-label="'Cellule ligne '+(r+1)+' colonne '+(c+1)" v-model="draft[r][c]" maxlength="2000" rows="3"/></td></tr></tbody></table></div><div class="text-dialog-actions"><small>Ctrl/⌘ Entrée : valider · Échap : annuler</small><button class="btn" type="button" @click="emit('close')">Annuler</button><button class="btn primary" type="submit"><Check :size="16"/>Appliquer les cellules</button></div></form></div></template>
