<script setup>
import {ref,onMounted,onUnmounted,nextTick} from 'vue';
import {isHeaderCell} from '../tables.js';
import {X,Check} from 'lucide-vue-next';
const props=defineProps({table:Object});const emit=defineEmits(['confirm','close']);const draft=ref(props.table.cells.map(row=>row.slice())),dialog=ref(null);let previous;
function confirm(){emit('confirm',draft.value.map(row=>row.slice()));}
function key(e){if(e.key==='Escape'){e.preventDefault();emit('close');}else if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();confirm();}else if(e.key==='Tab'){const list=[...dialog.value.querySelectorAll('button,textarea')].filter(el=>!el.disabled),first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
onMounted(()=>{previous=document.activeElement;nextTick(()=>dialog.value?.querySelector('textarea')?.focus());});onUnmounted(()=>previous?.focus?.());
</script>
<template><div class="modal-backdrop" @keydown.stop="key" @pointerdown.stop><form ref="dialog" class="table-dialog" role="dialog" aria-modal="true" aria-labelledby="table-dialog-title" @submit.prevent="confirm"><div class="text-dialog-heading"><div><h2 id="table-dialog-title">Modifier les cellules</h2><p>{{table.rows}} lignes × {{table.columns}} colonnes · texte multiligne</p></div><button type="button" class="icon-btn" aria-label="Fermer sans appliquer" @click="emit('close')"><X :size="20"/></button></div><div class="table-cell-scroll"><table><tbody><tr v-for="(row,r) in draft" :key="r"><td v-for="(_,c) in row" :key="c" :class="{headerCell:isHeaderCell(table,r,c)}"><label>L{{r+1}} · C{{c+1}} {{isHeaderCell(table,r,c)?'· En-tête':''}}<textarea :aria-label="'Cellule ligne '+(r+1)+' colonne '+(c+1)" v-model="draft[r][c]" maxlength="2000" rows="3"/></label></td></tr></tbody></table></div><div class="text-dialog-actions"><small>Ctrl/⌘ Entrée : valider · Échap : annuler</small><button class="btn" type="button" @click="emit('close')">Annuler</button><button class="btn primary" type="submit"><Check :size="16"/>Appliquer les cellules</button></div></form></div></template>
