<script setup>
import NumberRange from './NumberRange.vue';
import TextSpacing from './TextSpacing.vue';
import TextAlignment from './TextAlignment.vue';
import { fontWeights,weightNames,textMarkCss } from '../textStyles.js';
import { themeColors } from '../themes.js';
import { fontCss, fonts } from '../fonts.js';
const props=defineProps({value:Object,font:String,type:String,theme:Object,mode:{type:String,default:'style'}});const emit=defineEmits(['change']);
function color(e,commit=false){if(/^#[\da-f]{6}$/i.test(e.target.value))emit('change','highlightColor',e.target.value);else if(commit)e.target.value=props.value.highlightColor;}
</script>
<template><div class="text-styles"><template v-if="mode==='colors'"><label>Couleur du texte<select :value="value.colorRole||''" aria-label="Couleur du texte dans le thème" @change="emit('change','colorRole',$event.target.value||null);emit('change','color',null)"><option value="">Automatique</option><option v-for="c in themeColors(theme)" :key="c.id" :value="c.id">{{c.name}}</option></select></label><div class="theme-text-swatches"><button v-for="c in themeColors(theme)" :key="c.id" :style="{background:c.color}" :title="c.name" :aria-label="'Texte : '+c.name" :aria-pressed="value.colorRole===c.id" @click="emit('change','colorRole',c.id);emit('change','color',null)"></button></div><label>Couleur personnalisée<input type="color" :value="value.color||theme.ink" @input="emit('change','colorRole',null);emit('change','color',$event.target.value)"></label></template><template v-if="mode!=='colors'"><TextAlignment v-if="type!=='code'" :value="value.align" @change="emit('change','align',$event)"/><TextSpacing :value="value" @change="(key,v)=>emit('change',key,v)"/><label>Graisse<select :value="value.weight" aria-label="Graisse du texte" @change="emit('change','weight',Number($event.target.value))"><option v-for="weight in fontWeights(font,type)" :key="weight" :value="weight">{{weight}} · {{weightNames[weight]}}</option></select></label><div class="text-style-buttons"><button v-for="[key,label,icon] in [['italic','Italique','I'],['underline','Souligné','S'],['strike','Barré','B'],['highlight','Surligné','▰']]" :key="key" :class="[key,{active:value[key]}]" :aria-label="label" :aria-pressed="value[key]" :title="label" @click="emit('change',key,!value[key])">{{icon}}</button></div><p v-if="value.italic&&fonts.find(f=>f.id===font)?.italic===false" class="field-help">Cette police utilise une inclinaison synthétique.</p><template v-if="value.highlight"><label>Couleur du surlignage<div class="shape-color"><input type="color" :value="value.highlightColor" aria-label="Couleur du surlignage" @input="emit('change','highlightColor',$event.target.value)"><input type="text" :value="value.highlightColor" aria-label="Surlignage hexadécimal" maxlength="7" @input="color" @change="color($event,true)"></div></label><NumberRange label="Intensité du surlignage" unit="%" :model-value="value.highlightOpacity" @update:model-value="emit('change','highlightOpacity',$event)"/></template><p class="text-style-preview" :style="{fontFamily:fontCss(font,type),fontWeight:value.weight,fontStyle:value.italic?'italic':'normal',fontSynthesis:'style',letterSpacing:(value.letterSpacing||0)+'em',lineHeight:value.lineHeight??1.4}"><span :style="textMarkCss(value)">Java · Écrire et comprendre.</span></p><button class="btn full" @click="emit('change','reset')">Réinitialiser les effets</button><p class="field-help">Appliqué à tout le bloc sélectionné.</p></template></div></template>
