<script setup>
import {ref,nextTick,onMounted,onUnmounted} from 'vue';
import {toSuperscript,powerText,replaceSelection} from '../powers.js';
import {X,Check,Superscript} from 'lucide-vue-next';
const props=defineProps({value:String,label:String});const emit=defineEmits(['confirm','close']);
const draft=ref(props.value),labelDraft=ref(props.label||''),input=ref(null),dialog=ref(null);const powerOpen=ref(false),base=ref('2'),exponent=ref('23'),powerError=ref('');let previous,selection={start:0,end:0};
function rememberSelection(){if(input.value)selection={start:input.value.selectionStart,end:input.value.selectionEnd};}
function insert(value){const result=replaceSelection(draft.value,selection.start,selection.end,value);if(!result){powerError.value='Le texte dépasse la limite de 100 000 caractères.';return;}draft.value=result.text;powerError.value='';powerOpen.value=false;nextTick(()=>{input.value.focus();input.value.setSelectionRange(result.cursor,result.cursor);rememberSelection();});}
function insertPower(){const value=powerText(base.value,exponent.value);if(!value){powerError.value='Exposant : chiffres, signes + − =, parenthèses, n ou i.';return;}insert(value);}
function superscriptSelection(){const value=toSuperscript(draft.value.slice(selection.start,selection.end));if(value)insert(value);else {powerOpen.value=true;powerError.value='Sélectionne des chiffres, ou insère une puissance ci-dessous.';}}
function confirm(){emit('confirm',{text:draft.value,label:labelDraft.value});}
function key(e){if(e.key==='Escape'){e.preventDefault();emit('close');}else if(e.key==='Enter'&&e.target.closest('.power-form')&&!e.ctrlKey&&!e.metaKey){e.preventDefault();insertPower();}else if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();confirm();}else if(e.key==='Tab'){const list=[...dialog.value.querySelectorAll('button,input,textarea')].filter(el=>!el.disabled),first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
onMounted(()=>{previous=document.activeElement;nextTick(()=>input.value?.focus());});onUnmounted(()=>previous?.focus?.());
</script>
<template><div class="modal-backdrop text-dialog-backdrop" @keydown.stop="key" @pointerdown.stop><form ref="dialog" class="text-dialog" role="dialog" aria-modal="true" aria-labelledby="text-dialog-title" @submit.prevent="confirm"><div class="text-dialog-heading"><div><h2 id="text-dialog-title">Modifier le texte</h2><p>Le texte sera appliqué à la diapo après validation.</p></div><button type="button" class="icon-btn" aria-label="Fermer sans appliquer" @click="emit('close')"><X :size="20"/></button></div><label v-if="label!==undefined">Surtitre<input v-model="labelDraft" maxlength="100" aria-label="Surtitre du bloc"></label><div class="power-tools"><button type="button" class="btn" @click="powerOpen=!powerOpen;powerError=''" :aria-expanded="powerOpen"><Superscript :size="16"/>Insérer une puissance</button><button type="button" class="btn" @click="superscriptSelection">Sélection en exposant</button><span>2²³</span></div><div v-if="powerOpen" class="power-form"><label>Base<input v-model="base" aria-label="Base de la puissance" maxlength="100"></label><label>Exposant<input v-model="exponent" aria-label="Exposant de la puissance" maxlength="100"></label><button type="button" class="btn primary" @click="insertPower">Insérer</button></div><p v-if="powerError" class="power-error" role="status">{{powerError}}</p><label>Texte<textarea ref="input" v-model="draft" aria-label="Texte à appliquer" @select="rememberSelection" @keyup="rememberSelection" @click="rememberSelection" @input="rememberSelection" rows="10" maxlength="100000" spellcheck="true"/></label><div class="text-dialog-actions"><small>Ctrl/⌘ + Entrée pour valider · Échap pour annuler</small><button class="btn" type="button" @click="emit('close')">Annuler</button><button class="btn primary" type="submit"><Check :size="16"/>Appliquer</button></div></form></div></template>
