import test from 'node:test';
import assert from 'node:assert/strict';
import {selectionUnits,layoutUnits,arrangeUnits} from '../src/selection.js';
import {clampZoom,wheelZoom} from '../src/zoom.js';
const positions={a:{x:100,y:100,w:100,h:50},b:{x:140,y:160,w:60,h:40},c:{x:100,y:100,w:100,h:50},d:{x:140,y:160,w:60,h:40}};
const groups=[{id:'one',keys:['a','b']},{id:'two',keys:['c','d']}];
test('coincident multi-object components align as rigid units without overlapping',()=>{const units=selectionUnits(groups,Object.keys(positions),positions);assert.equal(units.length,2);const row={...positions,...layoutUnits(positions,units,'x',32)};assert.equal(row.b.x-row.a.x,40);assert.equal(row.b.y-row.a.y,60);assert.equal(row.d.x-row.c.x,40);assert.equal(row.d.y-row.c.y,60);assert.equal(row.c.x-row.a.x,132);assert.equal(row.c.y,row.a.y);assert.deepEqual(groups,[{id:'one',keys:['a','b']},{id:'two',keys:['c','d']}]);const column={...positions,...layoutUnits(positions,units,'y',24)};assert.equal(column.c.y-column.a.y,124);assert.equal(column.c.x,column.a.x);assert.equal(column.d.y-column.c.y,60);});
test('a selected member expands to the full component; rotation and internal offsets survive spacing',()=>{const p={...positions,b:{...positions.b,rotation:45}},units=selectionUnits(groups,['a','c'],p);assert.deepEqual(units.map(u=>u.keys),[['a','b'],['c','d']]);const result=arrangeUnits(p,units,'x','spacing',48);for(const [one,two] of [['a','b'],['c','d']]){assert.equal(result[two].x-result[one].x,p[two].x-p[one].x);assert.equal(result[two].y-result[one].y,p[two].y-p[one].y);}assert.equal(result.b.rotation,45);assert.deepEqual(layoutUnits(p,[units[0]],'x',20),{});});
test('zoom clamps to 25..300 and wheel handles trackpads, lines and limits',()=>{assert.equal(clampZoom(500),300);assert.equal(clampZoom(1),25);assert.equal(clampZoom(150),150);assert.ok(wheelZoom(100,{deltaY:-100,deltaMode:0})>100);assert.ok(wheelZoom(100,{deltaY:100,deltaMode:0})<100);assert.equal(wheelZoom(300,{deltaY:-100,deltaMode:0}),300);assert.equal(wheelZoom(25,{deltaY:100,deltaMode:0}),25);assert.ok(wheelZoom(100,{deltaY:-3,deltaMode:1})>100);});
