import test from 'node:test';
import assert from 'node:assert/strict';
import {deflateSync} from 'node:zlib';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {normalizeClip,clipTrack,clipMotion} from '../src/overlayAnimation.js';
import {normalizeOverlay,makeOverlay} from '../src/overlays.js';
import {appearanceRows} from '../src/appearances.js';
import {renderOverlayFrame,exportTransparentMovie,exportChromaMovie} from '../src/overlayVideo.js';
import {pngMovie} from '../src/pngMovie.js';
const theme={bg:'#000000',panel:'#111111',ink:'#ffffff',muted:'#aaaaaa',accent:'#00ff00',secondary:'#ffffff'};
function context(){const painted=[],stack=[];const ctx=new Proxy({globalAlpha:1,fillStyle:'',save(){stack.push([this.globalAlpha,this.fillStyle]);},restore(){[this.globalAlpha,this.fillStyle]=stack.pop();},measureText(t){return {width:t.length*10};},fillText(t){painted.push([t,this.globalAlpha]);},fill(){painted.push(['fill',this.globalAlpha]);},fillRect(){painted.push(['background',this.fillStyle]);},createLinearGradient(){return {addColorStop(){}};}},{get(o,k){return k in o?o[k]:()=>{};}});return {ctx,painted};}
globalThis.Path2D=class {addPath(){}roundRect(){}};globalThis.DOMMatrix=class {};
test('clip settings survive JSON, stay bounded and leave slideshow appearances unchanged',()=>{const slide=makeOverlay('java-bits'),before=JSON.stringify(normalizeOverlay({type:'java-bits',slide}).slide.fragments),raw={type:'java-bits',slide,clip:{duration:4,background:'chroma',chroma:'#0000ff',tracks:{bitsValue:{start:.2,end:3.5,entry:.4,exit:.6,animation:'zoom',exitAnimation:'down'},missing:{start:1}}}};const restored=normalizeOverlay(JSON.parse(JSON.stringify(raw)));assert.equal(restored.clip.duration,4);assert.equal(restored.clip.tracks.bitsValue.end,3.5);assert.equal(restored.clip.tracks.missing,undefined);assert.equal(JSON.stringify(restored.slide.fragments),before);assert.equal(normalizeClip({duration:999}).duration,20);assert.equal(normalizeClip({duration:''}).duration,6);assert.equal(normalizeClip({chroma:'bad'}).chroma,'#00ff00');const t=clipTrack(normalizeClip({...raw.clip,duration:2},slide.blockKeys),'bitsValue');assert.ok(t.start+t.entry<=t.end-t.exit+1e-9);assert.ok(t.end<=2);});
test('arrival, hold and disappearance include order zero and synchronize groups',()=>{const s=makeOverlay('java-bits');s.groups=[{id:'group',keys:['textTitre','bitsValue']}];const rows=appearanceRows(s),clip=normalizeClip({duration:4,stagger:0,tracks:{textTitre:{start:1,end:3,entry:.5,exit:.5,animation:'zoom',exitAnimation:'left'},bitsValue:{start:0,end:4,entry:1,exit:1,animation:'up'}}},s.blockKeys);let states=clipMotion(s,clip,0,rows);assert.equal(states.bitsValue.visible,false);assert.equal(states.shapeCarte.alpha,0);states=clipMotion(s,clip,1.25,rows);assert.deepEqual(states.bitsValue,states.textTitre);assert.ok(states.bitsValue.alpha>0&&states.bitsValue.alpha<1);assert.ok(states.bitsValue.scale<1);states=clipMotion(s,clip,2,rows);assert.equal(states.bitsValue.alpha,1);states=clipMotion(s,clip,2.8,rows);assert.ok(states.bitsValue.alpha<1);assert.ok(states.bitsValue.x<0);assert.equal(clipMotion(s,clip,4,rows).bitsValue.visible,false);});
test('shared renderer multiplies opacity and exports alpha without the checkerboard',()=>{const s=makeOverlay('java-bits'),c=context(),clip=normalizeClip({stagger:0},s.blockKeys);s.positions.textTitre.opacity=50;renderOverlayFrame(c.ctx,s,theme,clip,.3,960,540);assert.ok(c.painted.some(([t,a])=>t==='Un octet. Huit bits.'&&a>0&&a<.5));assert.equal(c.painted.some(([t])=>t==='background'),false);c.painted.length=0;renderOverlayFrame(c.ctx,s,theme,{...clip,background:'chroma',chroma:'#0000ff'},1,960,540);assert.deepEqual(c.painted.find(([t])=>t==='background'),['background','#0000ff']);assert.equal(c.ctx.globalAlpha,1);});
test('transparent export has exact frame count, cancellation and resource bounds',async()=>{const s=makeOverlay('java-bits'),clip=normalizeClip({duration:2,stagger:0},s.blockKeys),c=context();let count=0;const canvas={width:8,height:8,getContext:()=>c.ctx,toBlob:fn=>{count++;fn(new Blob([new Uint8Array([1,2,3])],{type:'image/png'}));}},progress=[];const blob=await exportTransparentMovie({canvas,slide:s,theme,clip,onProgress:n=>progress.push(n)});assert.equal(count,60);assert.equal(blob.type,'video/quicktime');assert.equal(progress.at(-1),1);const controller=new AbortController();controller.abort();await assert.rejects(exportTransparentMovie({canvas,slide:s,theme,clip,signal:controller.signal}),{name:'AbortError'});assert.equal(count,60);assert.throws(()=>pngMovie([],{width:8,height:8}),/invalides/);assert.throws(()=>pngMovie([{size:300*1024*1024}],{width:8,height:8}),/256 Mo/);});
function png(alpha){const u32=n=>{const b=Buffer.alloc(4);b.writeUInt32BE(n);return b;};function crc(data){let c=0xffffffff;for(const b of data){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}const chunk=(type,data)=>{const body=Buffer.concat([Buffer.from(type),data]);return Buffer.concat([u32(data.length),body,u32(crc(body))]);};const ihdr=Buffer.concat([u32(2),u32(2),Buffer.from([8,6,0,0,0])]);const rows=Buffer.from([0,255,0,0,alpha,255,0,0,alpha,0,255,0,0,alpha,255,0,0,alpha]);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(rows)),chunk('IEND',Buffer.alloc(0))]);}
test('real MOV decodes with duration, dimensions and RGBA including partial alpha',async t=>{try{execFileSync('ffprobe',['-version'],{stdio:'ignore'});execFileSync('ffmpeg',['-version'],{stdio:'ignore'});}catch{t.skip('FFmpeg non disponible');return;}const dir=mkdtempSync(join(tmpdir(),'frame-mov-'));try{const frames=Array.from({length:60},(_,i)=>png(i===0||i===59?0:i<30?128:255)),blob=pngMovie(frames,{width:2,height:2,fps:30}),file=join(dir,'alpha.mov');writeFileSync(file,new Uint8Array(await blob.arrayBuffer()));const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',file],{encoding:'utf8'}));assert.equal(probe.streams[0].codec_name,'png');assert.equal(probe.streams[0].pix_fmt,'rgba');assert.equal(probe.streams[0].width,2);assert.equal(probe.streams[0].height,2);assert.equal(probe.streams[0].nb_frames,'60');assert.equal(Number(probe.format.duration),2);const pixels=execFileSync('ffmpeg',['-v','error','-i',file,'-f','rawvideo','-pix_fmt','rgba','pipe:1']);assert.equal(pixels.length,60*16);assert.equal(pixels[3],0);assert.equal(pixels[19],128);assert.equal(pixels[30*16+3],255);assert.equal(pixels[59*16+3],0);}finally{rmSync(dir,{recursive:true,force:true});}});

test('chroma cancellation stops recorder and tracks and removes listeners without emitting a result',async()=>{const oldRecorder=globalThis.MediaRecorder,oldDocument=globalThis.document,listeners=new Map();let stops=0,recording;
 globalThis.document={addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:name=>listeners.delete(name)};
 globalThis.MediaRecorder=class {static isTypeSupported(){return true;}constructor(){recording=this;this.state='inactive';}start(){this.state='recording';}stop(){this.state='inactive';this.onstop?.();}};
 try{const s=makeOverlay('java-bits'),clip=normalizeClip({duration:2},s.blockKeys),c=context(),controller=new AbortController(),canvas={width:8,height:8,getContext:()=>c.ctx,captureStream:()=>({getTracks:()=>[{stop:()=>stops++}]})};const promise=exportChromaMovie({canvas,slide:s,theme,clip,signal:controller.signal});controller.abort();await assert.rejects(promise,{name:'AbortError'});assert.equal(stops,1);assert.equal(recording.state,'inactive');assert.equal(listeners.size,0);}finally{globalThis.MediaRecorder=oldRecorder;globalThis.document=oldDocument;}});
