import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makeSlide,normalizeSlide,fragmentOrders} from '../src/model.js';
import {captureScene,sceneAt,presentationSequence,addPedagogicalStep,movePedagogicalStep,allScenes,MAX_PEDAGOGICAL_STEPS} from '../src/pedagogicalSteps.js';
import {renderSlide} from '../src/render.js';
import {ProjectHistory} from '../src/history.js';
test('independent states preserve text, groups, position, styles, notes and inserted/deleted objects',()=>{
 const slide=makeSlide();slide.groups=[{id:'g',keys:['title','body']}];slide.notes='Initial';slide.fragments.body.order=3;assert.equal(addPedagogicalStep(slide),1);const state=slide.pedagogicalSteps[0].scene;state.title='Résultat';state.positions.title.x+=100;state.positions.title.textStyle={color:'#ff0000'};state.notes='Après';state.hiddenKeys=['code'];state.emphasisKeys=['title'];state.elements.textNew={type:'text',text:'42'};state.positions.textNew={x:100,y:100,w:200,h:100,size:30};state.fragments.textNew={order:0,animation:'fade'};state.blockKeys.push('textNew');
 assert.notEqual(slide.title,state.title);assert.equal(slide.positions.title.x,128);assert.equal(slide.notes,'Initial');assert.ok(!slide.elements.textNew);assert.equal(state.fragments.body.order,0);assert.deepEqual(state.groups,slide.groups);state.groups[0].keys.pop();assert.equal(slide.groups[0].keys.length,2);
 const restored=normalizeSlide(JSON.parse(JSON.stringify(slide)));assert.equal(restored.pedagogicalSteps[0].scene.title,'Résultat');assert.equal(restored.pedagogicalSteps[0].scene.notes,'Après');assert.deepEqual(restored.pedagogicalSteps[0].scene.hiddenKeys,['code']);assert.deepEqual(restored.pedagogicalSteps[0].scene.emphasisKeys,['title']);assert.ok(restored.pedagogicalSteps[0].scene.elements.textNew);assert.equal(allScenes([restored]).length,2);
});
test('navigation combines each state and its ordered appearances, with exact reversible lookup',()=>{
 const s=makeSlide();s.fragments.body.order=2;addPedagogicalStep(s);s.pedagogicalSteps[0].scene.fragments.code.order=4;const sequence=presentationSequence(s,fragmentOrders);assert.deepEqual(sequence.map(i=>[i.scene,i.order]),[[0,0],[0,2],[1,0],[1,4]]);assert.equal(sceneAt(s,sequence[3].scene).title,s.title);s.pedagogicalSteps[0].scene.title='42';assert.equal(sceneAt(s,sequence[2].scene).title,'42');assert.equal(sceneAt(s,sequence[1].scene).title,s.title);
});
test('reorder, duplicate, capacity and normalization do not introduce nested steps or unsafe scene data',()=>{
 const s=makeSlide();addPedagogicalStep(s);s.pedagogicalSteps[0].name='A';addPedagogicalStep(s,1);s.pedagogicalSteps[1].name='B';assert.equal(movePedagogicalStep(s,2,-1),1);assert.deepEqual(s.pedagogicalSteps.map(i=>i.name),['B','A']);assert.ok(!captureScene(s).pedagogicalSteps);const copy=normalizeSlide(JSON.parse(JSON.stringify(s)));copy.pedagogicalSteps[0].scene.body='copy';assert.notEqual(s.pedagogicalSteps[0].scene.body,'copy');while(s.pedagogicalSteps.length<MAX_PEDAGOGICAL_STEPS)addPedagogicalStep(s);assert.equal(addPedagogicalStep(s),null);
 const normalized=normalizeSlide({...s,pedagogicalSteps:[{name:'bad',scene:{layout:'invalid'}},{id:'same',scene:{...captureScene(s),hiddenKeys:['not-an-object'],pedagogicalSteps:s.pedagogicalSteps}},{id:'same',scene:captureScene(s)}]});assert.equal(normalized.pedagogicalSteps.length,2);assert.notEqual(normalized.pedagogicalSteps[0].id,normalized.pedagogicalSteps[1].id);assert.ok(!normalized.pedagogicalSteps[0].scene.pedagogicalSteps);assert.deepEqual(normalized.pedagogicalSteps[0].scene.hiddenKeys,[]);
});
test('history restores a previous teaching state without sharing scene references',()=>{
 const s=makeSlide();const history=new ProjectHistory({slides:[s]});addPedagogicalStep(s);history.record({slides:[s]});s.pedagogicalSteps[0].scene.title='changed';history.record({slides:[s]});const previous=history.undo();assert.notEqual(previous.slides[0].pedagogicalSteps[0].scene.title,'changed');const again=history.redo();assert.equal(again.slides[0].pedagogicalSteps[0].scene.title,'changed');
});
test('public renderer hides objects and notes while focus is painted in the shared scene',()=>{
 const s=makeSlide('title');s.title='VISIBLE';s.body='HIDDEN';s.notes='PRIVATE';s.hiddenKeys=['body'];s.emphasisKeys=['title'];const painted=[],outlines=[],ctx=new Proxy({font:'',globalAlpha:1,measureText(t){return {width:t.length*8};},fillText(t){painted.push(t);},strokeRect(...args){outlines.push(args);},createLinearGradient(){return {addColorStop(){}};}},{get(o,k){return k in o?o[k]:()=>{};}});renderSlide(ctx,s,{ink:'#fff',accent:'#00ff00',secondary:'#111'},{transparent:true});assert.ok(painted.includes('VISIBLE'));assert.ok(!painted.includes('HIDDEN'));assert.ok(!painted.includes('PRIVATE'));assert.equal(outlines.length,1);renderSlide(ctx,s,{ink:'#fff',accent:'#00ff00',secondary:'#111'},{transparent:true,showHidden:true});assert.ok(painted.includes('HIDDEN'));
});
