import {test} from 'node:test';
import assert from 'node:assert/strict';
import {AudienceFrames,PresenterSession} from '../src/presenterSession.js';
function harness(){let painted=0;const messages=[],commands=[],statuses=[],notifications=[],child={closed:false,focus(){},close(){this.closed=true;},postMessage(data,origin){messages.push({data,origin});}},host={location:{origin:'https://frame.test',href:'https://frame.test/?irrelevant=1#x'},open(url){this.url=url;return child;}},p=new PresenterSession({host,bitmap:async()=>({width:1920,height:1080,close(){}}),notify:n=>notifications.push(n),command:c=>commands.push(c),status:(...args)=>statuses.push(args)});p.open();const receiver=new AudienceFrames({source:host,origin:host.location.origin,session:p.token,paint(){painted++;},ack:sequence=>p.receive({source:child,origin:host.location.origin,data:{type:'frame-audience-painted',session:p.token,sequence}})});return {p,host,child,messages,commands,statuses,notifications,receiver,painted:()=>painted,ready:()=>p.receive({source:child,origin:host.location.origin,data:{type:'frame-audience-ready',session:p.token}})};}
test('a second session receives only rendered frames, validates origin/source/token, and reports painting',async()=>{const h=harness();assert.ok(h.host.url.includes('frameAudience='));assert.ok(!h.host.url.includes('irrelevant'));h.p.receive({source:h.child,origin:'https://evil.test',data:{type:'frame-audience-ready',session:h.p.token}});assert.equal(h.p.ready,false);h.ready();await h.p.mirror({notes:'PRIVATE'},100);assert.deepEqual(Object.keys(h.messages[0].data).sort(),['bitmap','sequence','session','type']);assert.ok(!JSON.stringify(h.messages).includes('PRIVATE'));const data=h.messages[0].data;h.receiver.receive({source:h.host,origin:h.host.location.origin,data});assert.equal(h.p.receivedFrames,1);assert.equal(h.painted(),1);h.receiver.receive({source:h.host,origin:h.host.location.origin,data});assert.equal(h.painted(),1);});
test('public controls are accepted only for the bound session and known commands',()=>{const h=harness();for(const [source,origin,session,action] of [[{},h.host.location.origin,h.p.token,'advance'],[h.child,'https://evil.test',h.p.token,'advance'],[h.child,h.host.location.origin,'other','advance'],[h.child,h.host.location.origin,h.p.token,'delete']])h.p.receive({source,origin,data:{type:'frame-audience-command',session,action}});assert.deepEqual(h.commands,[]);h.p.receive({source:h.child,origin:h.host.location.origin,data:{type:'frame-audience-command',session:h.p.token,action:'retreat'}});assert.deepEqual(h.commands,['retreat']);});
test('closing during asynchronous frame creation disposes the frame and cannot send to a replacement window',async()=>{const h=harness();let resolve,closed=0;h.p.bitmap=()=>new Promise(r=>resolve=r);h.ready();const pending=h.p.mirror({},100);h.p.close();resolve({close(){closed++;}});await pending;assert.equal(closed,1);assert.equal(h.messages.length,0);assert.deepEqual(h.statuses.at(-1),[false,false]);});
test('throttled final updates are delivered and image bitmaps are closed after paint or failure',async()=>{const h=harness();let callback;h.p.schedule=cb=>{callback=cb;return 1;};h.p.now=()=>140;h.ready();await h.p.mirror({},100);await h.p.mirror({},110);assert.equal(h.messages.length,1);await callback();assert.equal(h.messages.length,2);let closed=0;const receiver=new AudienceFrames({source:h.host,origin:h.host.location.origin,session:h.p.token,paint(){throw Error('canvas');}});assert.throws(()=>receiver.receive({source:h.host,origin:h.host.location.origin,data:{type:'frame-audience-frame',session:h.p.token,sequence:1,bitmap:{close(){closed++;}}}}));assert.equal(closed,1);});
test('popup refusal and closure are visible and reopening creates a fresh token',()=>{const h=harness(),old=h.p.token;h.child.closed=true;h.p.heartbeat();assert.ok(h.notifications[0].includes('fermée'));h.host.open=()=>null;assert.equal(h.p.open(),false);assert.ok(h.notifications.at(-1).includes('bloque'));assert.notEqual(old,h.p.token);});
