import {test} from 'node:test';
import assert from 'node:assert/strict';
import {normalizeTable,tableTracks,setTableRowHeight,tableCellLayout,drawTable} from '../src/tables.js';
import {wrapLines} from '../src/render.js';
import {boundedNumber} from '../src/numericControls.js';
import {makeSlide,normalizeSlide} from '../src/model.js';
import {copyObjects,pasteObjects} from '../src/objectSelection.js';
function context(){return {font:'',textBaseline:'top',globalAlpha:1,save(){},restore(){},beginPath(){},roundRect(){},rect(){},clip(){},fillRect(){},setLineDash(){},moveTo(){},lineTo(){},stroke(){},measureText(text){const size=Number(this.font.match(/([\d.]+)px/)?.[1]||30);return {width:[...text].length*(size*.5+parseFloat(this.letterSpacing||'0')),actualBoundingBoxAscent:this.textBaseline==='alphabetic'?size*.8:-size*.2,actualBoundingBoxDescent:this.textBaseline==='alphabetic'?size*.2:size};},fillText(){}};}
test('small cells fit full glyphs and multiline content without a padding clip hiding their bottom',()=>{const table=normalizeTable({fontSize:40,headerFontSize:40,padding:18}),ctx=context();for(const text of ['En-tête','Deux\nlignes','Une explication assez longue à retourner']){const layout=tableCellLayout(ctx,table,100,20,true,wrapLines,text);assert.equal(ctx.textBaseline,'alphabetic');assert.ok(layout.size<=40);assert.ok(layout.top>=0);assert.ok(layout.top+layout.contentHeight<=20.001);assert.ok(layout.lines.every(line=>ctx.measureText(line).width<=100-layout.padX*2+.001));}const clips=[];ctx.rect=(...args)=>clips.push(args);drawTable(ctx,normalizeTable({rows:1,columns:1,cells:[['Titre']],padding:18}),{x:12,y:24,w:100,h:20},{accent:'#0f0',bg:'#000',ink:'#fff',panel:'#000'},wrapLines);assert.deepEqual(clips,[[12,24,100,20]]);});
test('auto-fit can be disabled without hiding glyphs behind inner padding',()=>{const table=normalizeTable({fontSize:40,autoFitText:false}),layout=tableCellLayout(context(),table,200,20,false,wrapLines,'Texte');assert.equal(layout.size,40);assert.equal(normalizeTable({}).autoFitText,true);assert.equal(normalizeTable(table).autoFitText,false);});
test('common cell height resizes the table and an individual row preserves other row heights',()=>{const table=normalizeTable({rows:3,rowWeights:[1,2,1]}),position={x:10,y:20,w:300,h:400};assert.equal(setTableRowHeight(table,position,null,60),true);assert.equal(position.h,180);assert.deepEqual(tableTracks(table,position).rows.map(r=>r.size),[60,60,60]);setTableRowHeight(table,position,1,90);assert.equal(position.h,210);assert.deepEqual(tableTracks(table,position).rows.map(r=>Math.round(r.size)),[60,90,60]);assert.equal(setTableRowHeight(table,position,4,90),false);assert.equal(setTableRowHeight(table,position,null,NaN),false);assert.equal(setTableRowHeight(table,position,null,0),false);});
test('cell contents, adapted text option and individual heights survive JSON and clipboard independently',()=>{const s=makeSlide();s.elements.tableTest=normalizeTable({rows:2,cells:[['En-tête modifié'],['Texte\nmultiligne']],autoFitText:false});s.positions.tableTest={x:0,y:0,w:400,h:200,size:30};s.fragments.tableTest={order:0,animation:'fade'};s.blockKeys.push('tableTest');setTableRowHeight(s.elements.tableTest,s.positions.tableTest,1,150);const restored=normalizeSlide(JSON.parse(JSON.stringify(s)));assert.equal(restored.elements.tableTest.cells[1][0],'Texte\nmultiligne');assert.equal(restored.elements.tableTest.autoFitText,false);assert.ok(Math.abs(tableTracks(restored.elements.tableTest,restored.positions.tableTest).rows[1].size-150)<1e-8);const target=makeSlide(),[key]=pasteObjects(target,copyObjects(s,['tableTest']));target.elements[key].cells[0][0]='Indépendant';assert.equal(s.elements.tableTest.cells[0][0],'En-tête modifié');});
test('direct numeric entry accepts zero and fractions, clamps finite values and ignores blank/non numeric inputs',()=>{assert.equal(boundedNumber('50',0,100),50);assert.equal(boundedNumber('0',0,100),0);assert.equal(boundedNumber('0.3',.15,.8),.3);assert.equal(boundedNumber('300',0,100),100);assert.equal(boundedNumber('-20',0,100),0);for(const value of ['',null,undefined,'bad',Infinity])assert.equal(boundedNumber(value,0,100),null);});
