import {test} from 'node:test';
import assert from 'node:assert/strict';
import {normalizeTable,tableTextSizes,drawTable,resizeTableDivider,tableTracks,resizeTable,cellTextStyle} from '../src/tables.js';
import {wrapLines} from '../src/render.js';
import {usedFontFaces} from '../src/textStyles.js';
import {makeSlide,normalizeSlide} from '../src/model.js';
import {copyObjects,pasteObjects} from '../src/objectSelection.js';
function context(){return {font:'',letterSpacing:'0px',globalAlpha:1,textBaseline:'alphabetic',save(){},restore(){},beginPath(){},roundRect(){},rect(){},clip(){},fillRect(){},stroke(){},setLineDash(){},moveTo(){},lineTo(){},measureText(value){const size=Number(this.font.match(/([\d.]+)px/)?.[1]||20);return {width:[...value].length*(size*.55+parseFloat(this.letterSpacing||0)),actualBoundingBoxAscent:size*.8,actualBoundingBoxDescent:size*.2};},fillText(){}};}
test('Montserrat requested size never shrinks a column as it increases, and body cells use one fitted size',()=>{const e=normalizeTable({rows:1,columns:2,headerPosition:'none',font:'montserrat',padding:18,cells:[['Un texte long qui doit rester lisible sur plusieurs lignes','Court']]}),ctx=context(),p={x:0,y:0,w:440,h:85};let previous=0;for(let size=10;size<=120;size+=2){e.fontSize=size;const fit=tableTextSizes(ctx,e,p,wrapLines).body;assert.ok(fit>=previous-1e-4,`${previous} -> ${fit} for ${size}`);previous=fit;const calls=[];ctx.fillText=(text,x,y)=>calls.push(ctx.font);drawTable(ctx,e,p,{ink:'#fff',accent:'#0f0',panel:'#000',bg:'#000',muted:'#555'},wrapLines);assert.equal(new Set(calls).size,1);assert.ok(fit<=size);}e.autoFitText=false;e.fontSize=30;assert.equal(tableTextSizes(ctx,e,p,wrapLines).body,30);});
test('separator resizing preserves frame, adjacent pair sum, other tracks and minimum sizes including after normalization',()=>{const table=normalizeTable({rows:3,columns:3}),p={x:0,y:0,w:600,h:300},before=tableTracks(table,p);for(const axis of ['rows','columns']){const next=resizeTableDivider(table,p,axis,0,40);const after=tableTracks({...table,...next},p)[axis];assert.ok(Math.abs(after[2].size-before[axis][2].size)<1e-8);assert.ok(Math.abs(after[0].size-before[axis][0].size-40)<1e-8);assert.ok(Math.abs(after[1].size-before[axis][1].size+40)<1e-8);const bounded=resizeTableDivider(table,p,axis,0,100000);assert.ok(tableTracks({...table,...bounded},p)[axis][1].size>=7.99);}const huge={...p,w:10000};const extreme=normalizeTable({...table,...resizeTableDivider(table,huge,'columns',0,100000)});assert.ok(Math.abs(tableTracks(extreme,huge).columns[1].size-8)<1e-8);assert.equal(resizeTableDivider(table,p,'columns',2,10),null);});
test('cell styles validate, inherit header/body defaults and render only selected overrides',()=>{const e=normalizeTable({rows:2,columns:2,cells:[['A','B'],['C','D']],cellStyles:{'1:0':{font:'montserrat',fontSize:42,bold:true,align:'right',verticalAlign:'bottom',fill:'#ff0000',fillRole:null,textColor:'#ffffff',textColorRole:null},'1:1':{fontSize:NaN,align:'bad',fill:'bad'},'90:0':{fontSize:40}}});assert.equal(e.cellStyles['90:0'],undefined);assert.equal(e.cellStyles['1:1'].fontSize,30);assert.equal(e.cellStyles['1:1'].align,undefined);assert.equal(cellTextStyle(e,0,0).bold,true);assert.equal(cellTextStyle(e,1,0).fontSize,42);const ctx=context(),calls=[];ctx.fillText=(text,x,y)=>calls.push({text,font:ctx.font,align:ctx.textAlign,color:ctx.fillStyle});drawTable(ctx,e,{x:0,y:0,w:600,h:300},{ink:'#eee',accent:'#0f0',panel:'#000',bg:'#000',muted:'#555'},wrapLines);const c=calls.find(c=>c.text==='C');assert.match(c.font,/42px "Montserrat"/);assert.equal(c.align,'right');assert.equal(c.color,'#ffffff');assert.match(calls.find(c=>c.text==='D').font,/30px/);resizeTable(e,1,1);assert.deepEqual(e.cellStyles,{});});
test('cell overrides survive JSON, object copying and font preloading independently',()=>{const s=makeSlide();s.elements.tableTest=normalizeTable({rows:2,columns:2,cellStyles:{'1:0':{font:'montserrat',fontSize:40}}});s.positions.tableTest={x:0,y:0,w:600,h:200,size:30};s.blockKeys.push('tableTest');s.fragments.tableTest={order:0,animation:'fade'};const restored=normalizeSlide(JSON.parse(JSON.stringify(s)));assert.equal(restored.elements.tableTest.cellStyles['1:0'].fontSize,40);assert.ok(usedFontFaces([restored]).some(face=>face.id==='montserrat'&&face.weight===400));const target=makeSlide(),[key]=pasteObjects(target,copyObjects(s,['tableTest']));target.elements[key].cellStyles['1:0'].fontSize=60;assert.equal(s.elements.tableTest.cellStyles['1:0'].fontSize,40);});
