import {test} from 'node:test';
import assert from 'node:assert/strict';
import {normalizeTextSpacing,textLeading} from '../src/textSpacing.js';
import {normalizeTextStyle} from '../src/textStyles.js';
import {layoutText} from '../src/textLists.js';
import {text,wrapLines,autoTextBounds,blockBounds} from '../src/render.js';
import {makeSlide,normalizeSlide} from '../src/model.js';
import {normalizeTable,drawTable} from '../src/tables.js';
import {copyObjects,pasteObjects} from '../src/objectSelection.js';
import {addPedagogicalStep} from '../src/pedagogicalSteps.js';
function context(){return {letterSpacing:'0px',font:'',save(){},restore(){},measureText(value){const size=Number(this.font.match(/([\d.]+)px/)?.[1]||20);return {width:[...value].length*(size/2+parseFloat(this.letterSpacing)),actualBoundingBoxAscent:0,actualBoundingBoxDescent:size};},fillText(){},fillRect(){},beginPath(){},roundRect(){},rect(){},clip(){},stroke(){},setLineDash(){},moveTo(){},lineTo(){}};}
test('defaults preserve role leading, finite spacing is bounded and invalid imports cannot corrupt geometry',()=>{assert.deepEqual(normalizeTextSpacing(),{lineHeight:null,letterSpacing:0});assert.equal(textLeading({},1.12),1.12);assert.deepEqual(normalizeTextSpacing({lineHeight:10,letterSpacing:-20}),{lineHeight:3,letterSpacing:-.1});assert.deepEqual(normalizeTextSpacing({lineHeight:NaN,letterSpacing:Infinity}),{lineHeight:null,letterSpacing:0});assert.equal(normalizeTextStyle({lineHeight:2,letterSpacing:.12}).lineHeight,2);});
test('letter spacing controls wrapping, alignment, decoration width and line height controls layout',()=>{const ctx=context();ctx.font='400 20px Arial';let layout=layoutText(ctx,'AB CD\nEF',60,20,1.4,{lineHeight:2,letterSpacing:.2},wrapLines);assert.deepEqual(layout.rows.map(r=>r.text),['AB','CD','EF']);assert.deepEqual(layout.rows.map(r=>r.y),[0,40,80]);assert.equal(layout.height,120);layout=layoutText(ctx,'AB',100,20,1.4,{align:'right',letterSpacing:.2},wrapLines);assert.equal(layout.rows[0].x,72);const marks=[];ctx.fillRect=(...args)=>marks.push(args);text(ctx,'AB',0,0,100,20,'#fff',400,'Arial',1.4,{weight:400,letterSpacing:.2,underline:true});assert.equal(marks.at(-1)[2],28);text(ctx,'AB',0,0,100,20,'#fff');assert.equal(ctx.letterSpacing,'0px');});
test('auto-sized text and code bounds respond to spacing and preserve scaling',()=>{const s=makeSlide();s.title='AB\nCD';s.positions.title={x:0,y:0,w:200,size:20,autoSize:true,textStyle:{lineHeight:2,letterSpacing:.2}};const ctx=context(),b=autoTextBounds(ctx,s,'title');assert.equal(b.w,30);assert.equal(b.h,62);s.positions.title={...s.positions.title,contentScale:2,size:40,w:400};const scaled=autoTextBounds(ctx,s,'title');assert.equal(scaled.w,b.w*2);assert.equal(scaled.h,b.h*2);s.code='x\ny\nz\nw\nv';s.positions.code.h=undefined;s.positions.code.size=50;s.positions.code.textStyle={lineHeight:3};assert.equal(blockBounds(ctx,s,'code').h,865);});
test('spacing survives JSON, clipboard and independently editable teaching states',()=>{const s=makeSlide();s.positions.title.textStyle={lineHeight:1.8,letterSpacing:.08};addPedagogicalStep(s);s.pedagogicalSteps[0].scene.positions.title.textStyle.lineHeight=2.2;const restored=normalizeSlide(JSON.parse(JSON.stringify(s)));assert.equal(restored.positions.title.textStyle.lineHeight,1.8);assert.equal(restored.pedagogicalSteps[0].scene.positions.title.textStyle.lineHeight,2.2);const target=makeSlide(),keys=pasteObjects(target,copyObjects(s,['title']));assert.equal(target.positions[keys[0]].textStyle.letterSpacing,.08);});
test('table spacing uses relative units for wrapping and vertically aligned multiline cells',()=>{const table=normalizeTable({rows:1,columns:1,cells:[['AB\nCD']],fontSize:20,headerFontSize:20,lineHeight:2,letterSpacing:.1,padding:0,verticalAlign:'top',striped:false});const ctx=context(),calls=[];ctx.fillText=(value,x,y)=>calls.push([value,y,ctx.letterSpacing]);drawTable(ctx,table,{x:0,y:0,w:200,h:100},{ink:'#fff',accent:'#0f0',panel:'#000',bg:'#000'},wrapLines);assert.deepEqual(calls,[['AB',0,'2px'],['CD',40,'2px']]);assert.equal(normalizeTable(table).letterSpacing,.1);});
