import test from 'node:test';
import assert from 'node:assert/strict';
import {makeSlide,themes} from '../src/model.js';
import {makeOverlay} from '../src/overlays.js';
import {loadWorkspaces,saveWorkspaces,captureWorkspace,parseWorkspaceFile,workspaceKeys,normalizeWorkspace} from '../src/workspaceStorage.js';
import {ProjectFile} from '../src/projectFile.js';
function storage(initial={}){const data=new Map(Object.entries(initial));return {data,getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
const legacy=()=>({version:20,projectId:'original',project:'Cours Java',slides:[makeSlide()],banner:{type:'java-bits',slide:makeOverlay('java-bits'),clip:{duration:8,tracks:{bitsValue:{start:.2,end:7,entry:.4,exit:.4,animation:'zoom',exitAnimation:'fade'}}}},themes,themeId:'mint',projectColors:{accent:'#ee6655'},resolution:{width:1920,height:1080}});
test('legacy project migrates into separate documents without losing overlay, animation or slide session',()=>{const old=legacy();old.slides[0].title='Mon cours';old.banner.slide.elements.bitsValue.value='255';const local=storage({'frame-project':JSON.stringify(old),'frame-session':JSON.stringify({view:'banners',slideId:old.slides[0].id,workspace:'editor'})}),loaded=loadWorkspaces(local,[makeSlide()]);assert.equal(loaded.documents.slides.slides[0].title,'Mon cours');assert.equal(loaded.documents.banners.banner.slide.elements.bitsValue.value,'255');assert.equal(loaded.documents.banners.banner.clip.duration,8);assert.equal(loaded.session.scope,'banners');assert.equal(loaded.session.slideId,old.slides[0].id);assert.notEqual(loaded.documents.slides.projectId,loaded.documents.banners.projectId);assert.equal(loaded.documents.banners.projectId,'original');assert.equal(loaded.legacyScope,'banners');saveWorkspaces(local,loaded.documents,{...loaded.session,view:'banners'});assert.equal(local.getItem('frame-project'),null);const reloaded=loadWorkspaces(local,[makeSlide()]);assert.equal(reloaded.documents.banners.banner.clip.tracks.bitsValue.animation,'zoom');assert.equal(reloaded.documents.banners.projectId,'original');assert.equal(reloaded.session.scope,'banners');assert.equal(reloaded.legacyScope,null);});
test('scoped documents contain only their own content and retain independent settings',()=>{const data=legacy(),slide=captureWorkspace(data,'slides'),banner=captureWorkspace(data,'banners');assert.equal(slide.banner,undefined);assert.equal(banner.slides,undefined);banner.project='Incrustation Java';banner.themeId='violet';banner.projectColors={accent:'#5566ee'};const local=storage();saveWorkspaces(local,{slides:slide,banners:banner},{scope:'slides',view:'slides',slideId:data.slides[0].id,workspace:'canvas'});const loaded=loadWorkspaces(local,[makeSlide()]);assert.equal(loaded.documents.slides.project,'Cours Java');assert.equal(loaded.documents.banners.project,'Incrustation Java');assert.equal(loaded.documents.slides.themeId,'mint');assert.equal(loaded.documents.banners.themeId,'violet');assert.notEqual(loaded.documents.slides.projectColors.accent,loaded.documents.banners.projectColors.accent);const only=parseWorkspaceFile(JSON.parse(local.getItem(workspaceKeys.banners)));assert.deepEqual(Object.keys(only),['banners']);assert.equal(only.banners.banner.slide.elements.bitsValue.value,'151');const combined=parseWorkspaceFile(data);assert.deepEqual(Object.keys(combined),['slides','banners']);assert.throws(()=>parseWorkspaceFile({...banner,version:9}));assert.throws(()=>parseWorkspaceFile({...banner,kind:'bad'}));assert.throws(()=>normalizeWorkspace({...slide,kind:'banners'},'slides'));});
test('partial migration keeps legacy recovery data and an existing scoped document wins',()=>{const old=legacy(),local=storage({'frame-project':JSON.stringify(old)}),loaded=loadWorkspaces(local,[makeSlide()]),write=local.setItem;local.setItem=(key,value)=>{if(key===workspaceKeys.banners)throw Error('quota');write(key,value);};assert.throws(()=>saveWorkspaces(local,loaded.documents,{scope:'slides',view:'slides'}),/quota/);assert.ok(local.getItem('frame-project'));const deck=JSON.parse(local.getItem(workspaceKeys.slides));deck.slides[0].title='Plus récent';write(workspaceKeys.slides,JSON.stringify(deck));const again=loadWorkspaces(local,[makeSlide()]);assert.equal(again.documents.slides.slides[0].title,'Plus récent');assert.equal(again.documents.banners.banner.clip.duration,8);});
test('file handles restore independently, migrate legacy only into its slot and guard wrong document kind',async()=>{const records=new Map(),disks=new Map();let selected,suggested;function handle(name){disks.set(name,'');return {name,getFile:async()=>({text:async()=>disks.get(name)}),queryPermission:async()=> 'granted',createWritable:async()=>({write:async text=>disks.set(name,text),close:async()=>{}})};}const a=handle('deck.json'),b=handle('overlay.json'),memory=async(record,write=false,slot='active')=>write?records.set(slot,record):records.get(slot),api={showSaveFilePicker:async options=>{suggested=options.suggestedName;return selected;}},deck=new ProjectFile(api,memory,{slot:'active:slides',suggestedName:'frame-diaporama.json'}),overlay=new ProjectFile(api,memory,{slot:'active:banners',suggestedName:'frame-incrustation.json'}),data=legacy();selected=a;await deck.save(JSON.stringify(captureWorkspace(data,'slides')),'deck-id');assert.equal(suggested,'frame-diaporama.json');selected=b;await overlay.save(JSON.stringify(captureWorkspace(data,'banners')),'banner-id');assert.equal(suggested,'frame-incrustation.json');const resumed=new ProjectFile(api,memory,{slot:'active:slides'});await resumed.restore('deck-id');assert.equal(resumed.handle,a);const other=new ProjectFile(api,memory,{slot:'active:banners'});await other.restore('banner-id');assert.equal(other.handle,b);const before=disks.get('overlay.json');selected=b;await assert.rejects(deck.save(JSON.stringify(captureWorkspace(data,'slides')),'deck-id',true),/wrong-kind/);assert.equal(disks.get('overlay.json'),before);assert.equal(deck.handle,a);records.set('active',{handle:a,baseline:'legacy',projectId:'legacy-id'});const migrated=new ProjectFile(api,memory,{slot:'new',legacySlot:'active'});await migrated.restore('legacy-id');assert.equal(records.get('new').handle,a);const noMigration=new ProjectFile(api,memory,{slot:'unrelated'});await noMigration.restore('legacy-id');assert.equal(noMigration.handle,null);});
